import { useCallback, useEffect, useMemo, useState } from 'react';
import {
  FiActivity, FiAlertCircle, FiCalendar, FiCheck, FiChevronRight, FiClipboard, FiCreditCard,
  FiDollarSign, FiFileText, FiHome, FiRefreshCw, FiSettings, FiTool, FiUpload, FiUser, FiX,
} from 'react-icons/fi';
import { appApi, errorMessage } from '../services/api.js';

const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0));
const date = (value) => value ? new Intl.DateTimeFormat('pt-BR').format(new Date(`${String(value).slice(0, 10)}T12:00:00`)) : '—';
const dateTime = (value) => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
const statusText = { open: 'Aberto', in_progress: 'Em andamento', waiting: 'Aguardando', completed: 'Concluído', cancelled: 'Cancelado', pending: 'Pendente', processing: 'Processando', paid: 'Pago', active: 'Ativo', ended: 'Encerrado', awaiting_signature: 'Aguardando assinatura', draft: 'Rascunho' };
const docOptions = [
  ['identity', 'Documento de identificação'], ['address', 'Comprovante de endereço'], ['income', 'Comprovante de renda'],
  ['property', 'Documento do imóvel'], ['inspection', 'Vistoria'], ['contract', 'Contrato'], ['other', 'Outro documento'],
];
const terminationLabels = {
  notice: 'Aviso prévio registrado', final_charges: 'Cobranças finais conferidas', utilities: 'Água, energia e demais contas conferidas',
  exit_inspection: 'Vistoria de saída concluída', keys: 'Chaves devolvidas', deposit: 'Caução conferida/devolvida',
  repairs: 'Reparos e responsabilidades definidos', closing_term: 'Termo de encerramento concluído',
};

function ToneBadge({ value, children }) {
  return <span className={`ops-badge ${value || 'neutral'}`}>{children || statusText[value] || value}</span>;
}

function Empty({ icon: Icon = FiClipboard, title, text }) {
  return <div className="ops-empty"><Icon /><h3>{title}</h3><p>{text}</p></div>;
}

function Stat({ icon: Icon, label, value, hint }) {
  return <article className="ops-stat"><span><Icon /></span><div><small>{label}</small><strong>{value}</strong>{hint && <p>{hint}</p>}</div></article>;
}

function ActionCenter({ data, onLease }) {
  const items = data?.items || [];
  return <div className="ops-stack">
    <section className="ops-stats"><Stat icon={FiAlertCircle} label="Críticas" value={data?.counts?.critical || 0} hint="Ação imediata" /><Stat icon={FiActivity} label="Atenção" value={data?.counts?.attention || 0} hint="Requer acompanhamento" /><Stat icon={FiCalendar} label="Próximas" value={data?.counts?.upcoming || 0} hint="Nos próximos dias" /></section>
    <section className="ops-card"><header><div><span>Prioridades</span><h2>O que precisa ser feito</h2><p>Uma fila única para cobranças, assinaturas, documentos, reajustes, manutenção e encerramentos.</p></div></header>
      {items.length ? <div className="ops-task-list">{items.map((item, index) => <button key={`${item.type}-${item.lease_id}-${index}`} className="ops-task" onClick={() => item.lease_id && onLease(item.lease_id)}><span className={`ops-priority ${item.priority}`} /><div><div className="ops-task-title"><b>{item.title}</b><ToneBadge value={item.priority}>{item.priority === 'critical' ? 'Crítico' : item.priority === 'attention' ? 'Atenção' : 'Próximo'}</ToneBadge></div><p>{item.description}</p><small>{item.due_at ? `Prazo: ${date(item.due_at)}` : 'Sem prazo definido'}{item.property_name ? ` · ${item.property_name}` : ''}</small></div><FiChevronRight /></button>)}</div> : <Empty icon={FiCheck} title="Nenhuma pendência operacional" text="Quando algo exigir ação, a Locaio vai concentrar tudo aqui." />}
    </section>
  </div>;
}

function Portfolio({ data, onLease }) {
  const summary = data?.summary || {};
  const rows = data?.properties || [];
  return <div className="ops-stack">
    <section className="ops-stats four"><Stat icon={FiDollarSign} label="Previsto" value={money(summary.expected)} /><Stat icon={FiCheck} label="Recebido" value={money(summary.received)} /><Stat icon={FiAlertCircle} label="Em atraso" value={money(summary.overdue)} /><Stat icon={FiTool} label="Manutenção" value={money(summary.maintenance)} /></section>
    <section className="ops-card"><header><div><span>Carteira {data?.year || new Date().getFullYear()}</span><h2>Resultado por imóvel</h2><p>Receita, inadimplência, manutenção, caixa líquido e ocupação lado a lado.</p></div><div className="ops-big-number"><small>Caixa líquido</small><b>{money(summary.net_cash)}</b></div></header>
      {rows.length ? <div className="ops-property-finance">{rows.map((row) => <article key={row.property_id}><div className="ops-property-head"><span className="ops-property-icon"><FiHome /></span><div><h3>{row.property_name}</h3><small>{row.occupied ? 'Ocupado' : 'Disponível'} · {row.collection_rate == null ? 'Sem histórico suficiente' : `${row.collection_rate}% recebido`}</small></div><ToneBadge value={row.overdue > 0 ? 'attention' : 'completed'}>{row.overdue > 0 ? 'Atenção' : 'Em dia'}</ToneBadge></div><dl><div><dt>Recebido</dt><dd>{money(row.received)}</dd></div><div><dt>Atrasado</dt><dd>{money(row.overdue)}</dd></div><div><dt>Manutenção</dt><dd>{money(row.maintenance)}</dd></div><div><dt>Caixa líquido</dt><dd>{money(row.net_cash)}</dd></div></dl>{row.active_lease_id && <button className="ops-link" onClick={() => onLease(row.active_lease_id)}>Abrir locação <FiChevronRight /></button>}</article>)}</div> : <Empty icon={FiHome} title="Sem imóveis para analisar" text="Os indicadores financeiros aparecerão quando houver patrimônio e cobranças cadastradas." />}
    </section>
  </div>;
}

function TenantPortal({ data, pay, busy }) {
  const leases = data?.leases || [];
  return <div className="ops-stack"><section className="ops-card tenant-intro"><header><div><span>Área do inquilino</span><h2>Meu aluguel</h2><p>Contrato, vencimentos, pagamentos, documentos e chamados em uma área simples para o locatário.</p></div><FiUser /></header></section>
    {leases.length ? leases.map((entry) => <section className="ops-card" key={entry.lease.id}><header><div><span>{entry.lease.property_name}</span><h2>{entry.lease.tenant_name}</h2><p>{entry.lease.street}{entry.lease.number ? `, ${entry.lease.number}` : ''} · {entry.lease.city}/{entry.lease.state}</p></div><ToneBadge value={entry.lease.status}>{statusText[entry.lease.status] || entry.lease.status}</ToneBadge></header>
      <div className="ops-tenant-grid"><div><h3>Próximos vencimentos</h3>{entry.next_charges?.length ? entry.next_charges.slice(0, 6).map((charge) => <div className="ops-compact-row" key={charge.id}><div><b>{charge.description}</b><small>{date(charge.due_date)}</small></div><strong>{money(charge.amount)}</strong><div className="ops-pay-actions"><button disabled={busy} onClick={() => pay(entry.lease.id, charge.id, 'pix')}>Pix</button><button disabled={busy} onClick={() => pay(entry.lease.id, charge.id, 'boleto')}>Boleto</button></div></div>) : <p className="ops-muted">Nenhuma cobrança pendente.</p>}</div><div><h3>Documentos</h3>{entry.documents?.length ? entry.documents.slice(0, 8).map((document) => <div className="ops-compact-row" key={document.id}><FiFileText /><div><b>{document.name}</b><small>{document.category}</small></div><ToneBadge value={document.status}>{statusText[document.status] || document.status}</ToneBadge></div>) : <p className="ops-muted">Nenhum documento enviado.</p>}<h3 className="ops-section-gap">Chamados</h3>{entry.maintenance?.length ? entry.maintenance.slice(0, 5).map((item) => <div className="ops-compact-row" key={item.id}><FiTool /><div><b>{item.title}</b><small>{statusText[item.status] || item.status}</small></div></div>) : <p className="ops-muted">Nenhum chamado de manutenção.</p>}</div></div>
    </section>) : <Empty icon={FiUser} title="Nenhuma locação como inquilino" text="Essa área é preenchida automaticamente quando sua conta estiver vinculada como locatário de um contrato." />}
  </div>;
}

function Timeline({ items }) {
  return <section className="ops-subcard"><div className="ops-subhead"><div><span>Histórico</span><h3>Linha do tempo</h3></div></div>{items?.length ? <div className="ops-timeline">{items.map((item, index) => <div key={`${item.type}-${item.at}-${index}`}><span className="ops-timeline-dot" /><div><small>{dateTime(item.at)}</small><b>{item.title}</b><p>{item.description}</p></div></div>)}</div> : <Empty icon={FiActivity} title="Sem histórico" text="Os principais eventos da locação aparecerão aqui." />}</section>;
}

function DocumentsPanel({ requirements, leaseId, notify, refresh }) {
  const [category, setCategory] = useState('identity'); const [uploading, setUploading] = useState(false); const [editing, setEditing] = useState(false);
  const [selected, setSelected] = useState(['identity', 'address', 'income']);
  useEffect(() => { if (requirements?.requirements?.length) setSelected(requirements.requirements.map((item) => item.category)); }, [requirements]);
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; const body = new FormData(); body.append('category', category); body.append('file', file); setUploading(true); try { await appApi.post(`/leases/${leaseId}/documents`, body, { headers: { 'Content-Type': 'multipart/form-data' } }); notify('Documento enviado.'); await refresh(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setUploading(false); event.target.value = ''; } };
  const saveRequirements = async () => { const rows = selected.map((key) => ({ category: key, label: docOptions.find(([value]) => value === key)?.[1] || key, party: 'tenant', required: true })); if (!rows.length) return; try { await appApi.put(`/leases/${leaseId}/document-requirements`, { requirements: rows }); notify('Checklist documental atualizado.'); setEditing(false); await refresh(); } catch (error) { notify(errorMessage(error), 'error'); } };
  return <section className="ops-subcard"><div className="ops-subhead"><div><span>Documentação inteligente</span><h3>Checklist de documentos</h3></div><button className="ops-small-button" onClick={() => setEditing((value) => !value)}><FiSettings /> Configurar</button></div>
    {editing && <div className="ops-config-box"><p>Escolha o que será obrigatório nesta locação.</p><div className="ops-check-grid">{docOptions.slice(0, 6).map(([key, label]) => <label key={key}><input type="checkbox" checked={selected.includes(key)} onChange={() => setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key])} /> {label}</label>)}</div><button className="ops-primary" onClick={saveRequirements}>Salvar requisitos</button></div>}
    <div className="ops-requirements">{requirements?.requirements?.map((item) => <article key={item.category} className={item.fulfilled ? 'done' : ''}><span>{item.fulfilled ? <FiCheck /> : <FiAlertCircle />}</span><div><b>{item.label}</b><small>{item.fulfilled ? `${item.documents.length} arquivo(s) recebido(s)` : 'Pendente'}</small></div></article>)}</div>
    <div className="ops-upload-line"><select value={category} onChange={(event) => setCategory(event.target.value)}>{docOptions.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><label className="ops-primary"><FiUpload /> {uploading ? 'Enviando…' : 'Enviar arquivo'}<input hidden type="file" accept="image/*,.pdf" disabled={uploading} onChange={upload} /></label></div>
  </section>;
}

function AdjustmentPanel({ lease, leaseId, notify, refresh }) {
  const today = new Date().toISOString().slice(0, 10); const [form, setForm] = useState({ percentage: '', effective_on: today, index: lease?.adjustment_index || 'IPCA' }); const [preview, setPreview] = useState(null); const [busy, setBusy] = useState(false);
  const previewAdjustment = async () => { setBusy(true); try { const { data } = await appApi.post(`/leases/${leaseId}/adjustments/preview`, form); setPreview(data); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  const apply = async () => { setBusy(true); try { await appApi.post(`/leases/${leaseId}/adjustments`, form); notify('Reajuste aplicado às próximas cobranças pendentes.'); setPreview(null); setForm((current) => ({ ...current, percentage: '' })); await refresh(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  return <section className="ops-subcard"><div className="ops-subhead"><div><span>Reajuste</span><h3>Atualizar aluguel</h3></div><b>{money(lease?.rent_amount)}</b></div><div className="ops-form-row three"><label>Índice<input value={form.index} onChange={(e) => setForm({ ...form, index: e.target.value })} /></label><label>Percentual<input type="number" step="0.01" placeholder="Ex.: 4,25" value={form.percentage} onChange={(e) => setForm({ ...form, percentage: e.target.value })} /></label><label>Vigência<input type="date" value={form.effective_on} onChange={(e) => setForm({ ...form, effective_on: e.target.value })} /></label></div><button className="ops-secondary" disabled={busy || form.percentage === ''} onClick={previewAdjustment}>Calcular reajuste</button>{preview && <div className="ops-preview"><div><small>Atual</small><b>{money(preview.old_rent)}</b></div><FiChevronRight /><div><small>Novo aluguel</small><b>{money(preview.new_rent)}</b></div><div><small>Diferença</small><b>{money(preview.difference)}</b></div><div><small>Cobranças afetadas</small><b>{preview.future_charges_affected}</b></div><button className="ops-primary" disabled={busy} onClick={apply}>Aplicar reajuste</button></div>}</section>;
}

function MaintenancePanel({ items, leaseId, notify, refresh }) {
  const [form, setForm] = useState({ title: '', description: '', priority: 'normal', responsibility: 'undecided', estimated_cost: '' }); const [busy, setBusy] = useState(false);
  const create = async (event) => { event.preventDefault(); setBusy(true); try { await appApi.post(`/leases/${leaseId}/maintenance`, { ...form, estimated_cost: form.estimated_cost || null }); notify('Chamado de manutenção criado.'); setForm({ title: '', description: '', priority: 'normal', responsibility: 'undecided', estimated_cost: '' }); await refresh(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  const update = async (id, status) => { setBusy(true); try { await appApi.patch(`/leases/${leaseId}/maintenance/${id}`, { status }); notify('Manutenção atualizada.'); await refresh(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  return <section className="ops-subcard"><div className="ops-subhead"><div><span>Manutenção</span><h3>Chamados e reparos</h3></div></div><form className="ops-maintenance-form" onSubmit={create}><input required placeholder="Ex.: Vazamento na cozinha" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><textarea placeholder="Descreva o problema" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><div className="ops-form-row three"><label>Prioridade<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option value="low">Baixa</option><option value="normal">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></label><label>Responsabilidade<select value={form.responsibility} onChange={(e) => setForm({ ...form, responsibility: e.target.value })}><option value="undecided">A definir</option><option value="landlord">Locador</option><option value="tenant">Inquilino</option><option value="shared">Compartilhada</option></select></label><label>Custo estimado<input type="number" min="0" step="0.01" value={form.estimated_cost} onChange={(e) => setForm({ ...form, estimated_cost: e.target.value })} /></label></div><button className="ops-primary" disabled={busy}><FiTool /> Abrir chamado</button></form>
    {items?.length ? <div className="ops-maintenance-list">{items.map((item) => <article key={item.id}><div><ToneBadge value={item.status}>{statusText[item.status] || item.status}</ToneBadge><ToneBadge value={item.priority}>{item.priority === 'urgent' ? 'Urgente' : item.priority === 'high' ? 'Alta' : item.priority === 'low' ? 'Baixa' : 'Normal'}</ToneBadge><h4>{item.title}</h4><p>{item.description}</p><small>{item.payload?.responsibility ? `Responsabilidade: ${item.payload.responsibility}` : ''}{item.amount ? ` · ${money(item.amount)}` : ''}</small></div>{!['completed', 'cancelled'].includes(item.status) && <div className="ops-inline-actions"><button disabled={busy} onClick={() => update(item.id, 'in_progress')}>Em andamento</button><button disabled={busy} onClick={() => update(item.id, 'completed')}>Concluir</button></div>}</article>)}</div> : <p className="ops-muted">Nenhum chamado registrado.</p>}
  </section>;
}

function InspectionPanel({ lease, leaseId, items, notify, refresh }) {
  const today = new Date().toISOString().slice(0, 10); const [form, setForm] = useState({ type: 'entry', occurred_at: today, summary: '' }); const [busy, setBusy] = useState(false);
  const create = async (event) => { event.preventDefault(); setBusy(true); try { await appApi.post(`/properties/${lease.property_id}/inspections`, { ...form, lease_id: Number(leaseId), items: [] }); notify('Vistoria registrada.'); setForm((current) => ({ ...current, summary: '' })); await refresh(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  return <section className="ops-subcard"><div className="ops-subhead"><div><span>Vistorias</span><h3>Entrada, periódica e saída</h3></div></div><form className="ops-form-row inspection" onSubmit={create}><label>Tipo<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="entry">Entrada</option><option value="periodic">Periódica</option><option value="exit">Saída</option></select></label><label>Data<input type="date" value={form.occurred_at} onChange={(e) => setForm({ ...form, occurred_at: e.target.value })} /></label><label className="grow">Resumo<input required placeholder="Estado geral, medidores, chaves e observações" value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} /></label><button className="ops-primary" disabled={busy}><FiClipboard /> Registrar</button></form>{items?.length ? <div className="ops-inspection-list">{items.filter((item) => String(item.lease_id) === String(leaseId)).map((item) => <article key={item.id}><span><FiClipboard /></span><div><b>{item.type === 'entry' ? 'Vistoria de entrada' : item.type === 'exit' ? 'Vistoria de saída' : 'Vistoria periódica'}</b><p>{item.summary || 'Sem observações.'}</p><small>{date(item.occurred_at)}</small></div></article>)}</div> : <p className="ops-muted">Nenhuma vistoria registrada para este imóvel.</p>}</section>;
}

function TerminationPanel({ lease, leaseId, operation, notify, refresh }) {
  const [expected, setExpected] = useState(lease?.ends_on || new Date().toISOString().slice(0, 10)); const [reason, setReason] = useState(''); const [checklist, setChecklist] = useState(operation?.payload?.checklist || Object.fromEntries(Object.keys(terminationLabels).map((key) => [key, false]))); const [busy, setBusy] = useState(false);
  useEffect(() => { if (operation?.payload?.checklist) setChecklist(operation.payload.checklist); }, [operation]);
  const start = async () => { setBusy(true); try { await appApi.post(`/leases/${leaseId}/termination`, { expected_end_on: expected, reason }); notify('Checklist de encerramento iniciado.'); await refresh(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  const complete = async () => { setBusy(true); try { await appApi.post(`/leases/${leaseId}/termination/complete`, { checklist, ended_on: expected, notes: reason, confirm_end: true }); notify('Locação encerrada e imóvel liberado.'); await refresh(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  if (['ended', 'cancelled'].includes(lease?.status)) return <section className="ops-subcard"><div className="ops-subhead"><div><span>Encerramento</span><h3>Locação encerrada</h3></div><ToneBadge value="completed">Concluído</ToneBadge></div><p className="ops-muted">O histórico permanece disponível na linha do tempo.</p></section>;
  return <section className="ops-subcard"><div className="ops-subhead"><div><span>Encerramento assistido</span><h3>Checklist de saída</h3></div>{operation && <ToneBadge value={operation.status}>{statusText[operation.status] || operation.status}</ToneBadge>}</div>{!operation ? <div className="ops-termination-start"><div className="ops-form-row two"><label>Data prevista<input type="date" value={expected} onChange={(e) => setExpected(e.target.value)} /></label><label>Motivo / observação<input value={reason} onChange={(e) => setReason(e.target.value)} /></label></div><button className="ops-secondary" disabled={busy} onClick={start}>Iniciar encerramento</button></div> : <><div className="ops-checklist">{Object.entries(terminationLabels).map(([key, label]) => <label key={key}><input type="checkbox" checked={Boolean(checklist[key])} onChange={() => setChecklist((current) => ({ ...current, [key]: !current[key] }))} /><span>{label}</span></label>)}</div><div className="ops-form-row two"><label>Data efetiva<input type="date" value={expected} onChange={(e) => setExpected(e.target.value)} /></label><label>Observações<input value={reason} onChange={(e) => setReason(e.target.value)} /></label></div><div className="ops-termination-footer"><small>{Object.values(checklist).filter(Boolean).length} de {Object.keys(checklist).length} etapas concluídas</small><button className="ops-danger" disabled={busy || Object.values(checklist).some((value) => !value)} onClick={complete}>Concluir e liberar imóvel</button></div></>}</section>;
}

function LeaseLifecycle({ leaseId, leases, notify, onRefreshOverview }) {
  const [loading, setLoading] = useState(true); const [detail, setDetail] = useState(null); const [timeline, setTimeline] = useState([]); const [requirements, setRequirements] = useState(null); const [maintenance, setMaintenance] = useState([]); const [termination, setTermination] = useState(null); const [inspections, setInspections] = useState([]); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!leaseId) return; setLoading(true); try { const leaseResponse = await appApi.get(`/leases/${leaseId}`); const leaseData = leaseResponse.data; const propertyId = leaseData?.lease?.property_id; const [timelineResponse, requirementsResponse, maintenanceResponse, terminationResponse, inspectionResponse] = await Promise.all([appApi.get(`/leases/${leaseId}/timeline`), appApi.get(`/leases/${leaseId}/document-requirements`), appApi.get(`/leases/${leaseId}/maintenance`), appApi.get(`/leases/${leaseId}/termination`), propertyId ? appApi.get(`/properties/${propertyId}/inspections`) : Promise.resolve({ data: [] })]); setDetail(leaseData); setTimeline(timelineResponse.data || []); setRequirements(requirementsResponse.data); setMaintenance(maintenanceResponse.data || []); setTermination(terminationResponse.data); setInspections(inspectionResponse.data || []); } catch (error) { notify(errorMessage(error), 'error'); } finally { setLoading(false); } }, [leaseId, notify]);
  useEffect(() => { load(); }, [load]);
  const refresh = async () => { await load(); await onRefreshOverview(); };
  const ensureSchedule = async () => { setBusy(true); try { const { data } = await appApi.post(`/leases/${leaseId}/charges/schedule`); notify(data.created ? `${data.created} cobrança(s) criada(s).` : 'Cronograma já estava atualizado.'); await refresh(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  if (!leaseId) return <Empty icon={FiHome} title="Selecione uma locação" text="Escolha um contrato para acompanhar toda a jornada operacional." />;
  if (loading || !detail) return <div className="ops-loading"><span /><p>Carregando ciclo da locação…</p></div>;
  const lease = detail.lease; const property = detail.property; const selected = leases.find((item) => String(item.id) === String(leaseId));
  return <div className="ops-stack"><section className="ops-card lease-summary"><header><div><span>Ciclo da locação</span><h2>{property?.name || selected?.property_name || `Locação #${leaseId}`}</h2><p>{lease.tenant_name} · {date(lease.starts_on)} até {date(lease.ends_on)}</p></div><div className="ops-summary-actions"><ToneBadge value={lease.status}>{statusText[lease.status] || lease.status}</ToneBadge><button className="ops-secondary" disabled={busy} onClick={ensureSchedule}><FiRefreshCw /> Garantir cobranças</button></div></header><section className="ops-stats compact"><Stat icon={FiDollarSign} label="Aluguel" value={money(lease.rent_amount)} /><Stat icon={FiCreditCard} label="Cobranças" value={detail.charges?.length || 0} /><Stat icon={FiFileText} label="Documentos" value={detail.documents?.length || 0} /><Stat icon={FiCheck} label="Assinaturas" value={detail.signatures?.length || 0} /></section></section>
    <Timeline items={timeline} /><DocumentsPanel requirements={requirements} leaseId={leaseId} notify={notify} refresh={refresh} /><AdjustmentPanel lease={lease} leaseId={leaseId} notify={notify} refresh={refresh} /><MaintenancePanel items={maintenance} leaseId={leaseId} notify={notify} refresh={refresh} /><InspectionPanel lease={lease} leaseId={leaseId} items={inspections} notify={notify} refresh={refresh} /><TerminationPanel lease={lease} leaseId={leaseId} operation={termination} notify={notify} refresh={refresh} />
  </div>;
}

export default function OperationsExperience({ children }) {
  const [open, setOpen] = useState(false); const [tab, setTab] = useState('actions'); const [loading, setLoading] = useState(false); const [actionCenter, setActionCenter] = useState(null); const [portfolio, setPortfolio] = useState(null); const [portal, setPortal] = useState(null); const [leases, setLeases] = useState([]); const [selectedLease, setSelectedLease] = useState(null); const [toast, setToast] = useState(null); const [busy, setBusy] = useState(false);
  const notify = useCallback((message, type = 'success') => { setToast({ message, type }); window.clearTimeout(window.__locaioOpsToast); window.__locaioOpsToast = window.setTimeout(() => setToast(null), 4200); }, []);
  const loadOverview = useCallback(async (silent = false) => { if (!localStorage.getItem('token')) return; if (!silent) setLoading(true); try { const [actions, finances, tenant, leaseList] = await Promise.all([appApi.get('/leasing/action-center'), appApi.get('/leasing/portfolio'), appApi.get('/leasing/tenant-portal'), appApi.get('/leases')]); setActionCenter(actions.data); setPortfolio(finances.data); setPortal(tenant.data); setLeases(leaseList.data || []); if (!selectedLease && leaseList.data?.length) setSelectedLease(leaseList.data[0].id); } catch (error) { if (open) notify(errorMessage(error, 'Não foi possível carregar a central de operação.'), 'error'); } finally { if (!silent) setLoading(false); } }, [notify, open, selectedLease]);
  useEffect(() => { if (localStorage.getItem('token')) loadOverview(true); const handler = () => loadOverview(true); window.addEventListener('authChanged', handler); return () => window.removeEventListener('authChanged', handler); }, [loadOverview]);
  useEffect(() => { if (open) loadOverview(); }, [open]); // eslint-disable-line react-hooks/exhaustive-deps
  const totalPending = Number(actionCenter?.counts?.critical || 0) + Number(actionCenter?.counts?.attention || 0);
  const openLease = (id) => { setSelectedLease(id); setTab('lifecycle'); };
  const pay = async (leaseId, chargeId, method) => { setBusy(true); try { await appApi.post(`/leases/${leaseId}/charges/${chargeId}/payment`, { method }); notify(`Pagamento preparado via ${method === 'pix' ? 'Pix' : method === 'boleto' ? 'boleto' : 'cartão'}.`); await loadOverview(true); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  const tabs = [['actions', FiActivity, 'Pendências'], ['portfolio', FiDollarSign, 'Financeiro'], ['lifecycle', FiClipboard, 'Locações'], ['tenant', FiUser, 'Inquilino']];
  return <>{children}<button className="ops-launcher" onClick={() => setOpen(true)} aria-label="Abrir Central de Operação"><FiActivity /><span>Operação</span>{totalPending > 0 && <b>{totalPending > 99 ? '99+' : totalPending}</b>}</button>{open && <div className="ops-overlay"><aside className="ops-panel"><header className="ops-panel-head"><div><span className="ops-kicker">Locaio inteligente</span><h1>Central de Operação</h1><p>Decida e execute sem procurar informação em várias telas.</p></div><button className="ops-close" onClick={() => setOpen(false)}><FiX /></button></header><nav className="ops-tabs">{tabs.map(([key, Icon, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}><Icon /><span>{label}</span>{key === 'actions' && totalPending > 0 && <b>{totalPending}</b>}</button>)}</nav>{tab === 'lifecycle' && <div className="ops-lease-picker"><label>Locação<select value={selectedLease || ''} onChange={(e) => setSelectedLease(Number(e.target.value))}>{leases.map((lease) => <option key={lease.id} value={lease.id}>{lease.property_name || `Imóvel #${lease.property_id}`} · {lease.tenant_name}</option>)}</select></label></div>}<main className="ops-body">{loading ? <div className="ops-loading"><span /><p>Organizando suas informações…</p></div> : tab === 'actions' ? <ActionCenter data={actionCenter} onLease={openLease} /> : tab === 'portfolio' ? <Portfolio data={portfolio} onLease={openLease} /> : tab === 'tenant' ? <TenantPortal data={portal} pay={pay} busy={busy} /> : <LeaseLifecycle leaseId={selectedLease} leases={leases} notify={notify} onRefreshOverview={() => loadOverview(true)} />}</main></aside></div>}{toast && <div className={`ops-toast ${toast.type}`}>{toast.message}</div>}</>;
}
