import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  FiActivity, FiAlertTriangle, FiArrowLeft, FiBarChart2, FiBox, FiCalendar, FiCamera, FiCheck,
  FiClock, FiDollarSign, FiDownload, FiEdit3, FiFileText, FiHome, FiKey, FiLayers, FiLink,
  FiMapPin, FiPlus, FiRefreshCw, FiSave, FiSearch, FiShield, FiTag, FiTool, FiTrash2,
  FiUpload, FiUser, FiUsers, FiX,
} from 'react-icons/fi';
import { appApi, errorMessage } from '../services/api.js';

const tabs = [
  ['overview', FiActivity, 'Inteligência'],
  ['financial', FiDollarSign, 'Financeiro'],
  ['lease', FiKey, 'Locação'],
  ['inspections', FiCamera, 'Vistorias'],
  ['files', FiFileText, 'Acervo'],
  ['maintenance', FiTool, 'Manutenção'],
  ['structure', FiLayers, 'Ambientes'],
  ['access', FiUsers, 'Acessos'],
  ['history', FiClock, 'Histórico'],
];

const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0));
const pct = (value) => value === null || value === undefined ? '—' : `${Number(value).toFixed(2).replace('.', ',')}%`;
const date = (value) => value ? new Intl.DateTimeFormat('pt-BR').format(new Date(`${String(value).slice(0, 10)}T12:00:00`)) : '—';
const dateTime = (value) => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
const localDateTime = () => { const d = new Date(); d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0, 16); };
const today = () => new Date().toISOString().slice(0, 10);
const futureDateTime = (days = 7) => { const d = new Date(); d.setDate(d.getDate() + days); d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0, 16); };
const bytes = (value) => { const n = Number(value || 0); if (n < 1024) return `${n} B`; if (n < 1048576) return `${(n / 1024).toFixed(1)} KB`; return `${(n / 1048576).toFixed(1)} MB`; };

const statusLabel = {
  available: 'Disponível', occupied: 'Ocupado', maintenance: 'Manutenção', inactive: 'Inativo', active: 'Ativo', draft: 'Rascunho',
  awaiting_documents: 'Aguardando documentos', awaiting_signature: 'Aguardando assinatura', ended: 'Encerrado', cancelled: 'Cancelado',
  pending: 'Pendente', processing: 'Processando', paid: 'Pago', planned: 'Planejado', open: 'Aberta', in_progress: 'Em andamento',
  waiting: 'Aguardando', completed: 'Concluída', excellent: 'Excelente', good: 'Boa', attention: 'Atenção', critical: 'Crítica',
};
const priorityLabel = { low: 'Baixa', normal: 'Normal', high: 'Alta', urgent: 'Urgente' };
const roleLabel = { owner: 'Proprietário', co_owner: 'Coproprietário', manager: 'Gerente', accountant: 'Contador', lawyer: 'Advogado', realtor: 'Corretor', provider: 'Prestador', tenant: 'Inquilino', viewer: 'Visualizador' };
const conditionLabel = { new: 'Novo', excellent: 'Excelente', good: 'Bom', fair: 'Regular', poor: 'Ruim', damaged: 'Danificado', missing: 'Ausente', ok: 'OK', not_recorded: 'Não registrado' };
const fileContextLabel = { general: 'Fotos gerais', entry_inspection: 'Vistoria de entrada', periodic_inspection: 'Vistoria periódica', exit_inspection: 'Vistoria de saída', maintenance: 'Manutenção', documents: 'Documentos', before_after: 'Antes / depois' };

function hasPermission(permissions, permission) { return permissions?.includes('*') || permissions?.includes(permission); }
function Badge({ value, priority = false }) { return <span className={`pwi-badge ${priority ? `priority-${value}` : `status-${value}`}`}>{priority ? priorityLabel[value] || value : statusLabel[value] || value || '—'}</span>; }
function Empty({ icon: Icon = FiHome, title, description, action }) { return <div className="pwi-empty"><span><Icon /></span><h3>{title}</h3><p>{description}</p>{action}</div>; }
function Metric({ label, value, hint, tone = '' }) { return <article className={`pwi-metric ${tone}`}><small>{label}</small><strong>{value}</strong>{hint && <p>{hint}</p>}</article>; }
function SectionTitle({ eyebrow, title, description, action }) { return <div className="pwi-section-title"><div><span>{eyebrow}</span><h2>{title}</h2>{description && <p>{description}</p>}</div>{action}</div>; }
function Field({ label, children, span = false }) { return <label className={span ? 'span-2' : ''}><span>{label}</span>{children}</label>; }
function MiniTrend({ monthly = [] }) {
  const max = Math.max(1, ...monthly.map((m) => Math.max(Math.abs(Number(m.income || 0)), Math.abs(Number(m.expenses || 0)))));
  return <div className="pwi-trend">{monthly.map((item) => <div className="pwi-trend-col" key={item.month} title={`${item.month}: ${money(item.net)}`}><div className="pwi-trend-bars"><i className="income" style={{ height: `${Math.max(3, (Number(item.income || 0) / max) * 72)}px` }} /><i className="expense" style={{ height: `${Math.max(3, (Number(item.expenses || 0) / max) * 72)}px` }} /></div><small>{item.month.slice(5)}</small></div>)}</div>;
}

function OverviewTab({ data, profile, analytics, alerts, tags, permissions, onReload, notify }) {
  const [editProfile, setEditProfile] = useState(false);
  const [tagText, setTagText] = useState('');
  const [form, setForm] = useState(profile || {});
  useEffect(() => setForm(profile || {}), [profile]);
  const saveProfile = async (event) => { event.preventDefault(); try { await appApi.put(`/assets/property/${data.property.id}/profile`, { acquisition_value: form.acquisition_value || null, market_value: form.market_value || null, acquired_on: form.acquired_on || null, insurance_expires_on: form.insurance_expires_on || null, document_expires_on: form.document_expires_on || null, registry_reference: form.registry_reference || null }); notify('Perfil patrimonial atualizado.'); setEditProfile(false); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const saveTags = async () => { const values = tagText.split(',').map((x) => x.trim()).filter(Boolean); try { await appApi.put(`/assets/property/${data.property.id}/tags`, { tags: values }); notify('Tags atualizadas.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  useEffect(() => setTagText((tags || []).map((t) => t.tag || t).join(', ')), [tags]);
  const health = analytics.health || data.health || {};
  const occupancy = analytics.occupancy || {};
  const financial = analytics.financial || {};
  return <div className="pwi-tab-content">
    <section className="pwi-health-hero">
      <div className={`pwi-health-score grade-${health.grade || 'good'}`}><span>Saúde do imóvel</span><strong>{health.score ?? '—'}<small>/100</small></strong><b>{statusLabel[health.grade] || health.grade || 'Sem avaliação'}</b></div>
      <div className="pwi-health-body"><span className="pwi-eyebrow">Decisão rápida</span><h2>{alerts.length ? `${alerts.length} ponto(s) merecem atenção` : 'Patrimônio sob controle'}</h2><p>O score cruza recebimentos, vacância, manutenção, vistorias, documentação, seguro e dados patrimoniais.</p><div className="pwi-positive-row">{(health.positive_factors || []).slice(0, 4).map((item) => <span key={item}><FiCheck /> {item}</span>)}</div></div>
    </section>
    <section className="pwi-metrics">
      <Metric label="Ocupação · 12 meses" value={pct(occupancy.occupancy_rate_12m)} hint={`${occupancy.occupied_days_12m || 0} dias ocupados`} tone="blue" />
      <Metric label="Vacância atual" value={`${occupancy.vacancy_days || 0} dias`} hint={occupancy.average_vacancy_between_leases !== null && occupancy.average_vacancy_between_leases !== undefined ? `Média histórica: ${occupancy.average_vacancy_between_leases} dias` : 'Sem histórico suficiente'} tone={occupancy.vacancy_days > 30 ? 'warning' : 'success'} />
      <Metric label="Resultado líquido · 12m" value={money(financial.net_result_12m)} hint={`${money(financial.gross_income_12m)} de receita bruta`} tone={Number(financial.net_result_12m) >= 0 ? 'success' : 'danger'} />
      <Metric label="Rentabilidade líquida" value={pct(financial.net_yield_12m)} hint={profile.market_value || profile.acquisition_value ? 'Sobre o valor patrimonial informado' : 'Informe valor de aquisição/mercado'} />
      <Metric label="Inadimplência" value={pct(financial.delinquency_rate || 0)} hint={`${money(financial.overdue)} vencido`} tone={Number(financial.overdue) > 0 ? 'danger' : 'success'} />
      <Metric label="Manutenção · 12m" value={money(financial.maintenance_cost_12m)} hint="Custos concluídos" />
    </section>
    <section className="pwi-grid-two">
      <article className="pwi-card">
        <SectionTitle eyebrow="Alertas automáticos" title="O que precisa da sua atenção" description="Priorizado por criticidade e prazo." />
        {alerts.length ? <div className="pwi-alert-list">{alerts.slice(0, 10).map((alert, index) => <div className={`pwi-alert ${alert.severity}`} key={`${alert.key}-${index}`}><span><FiAlertTriangle /></span><div><b>{alert.title}</b><p>{alert.message}</p>{alert.dueAt && <small>{date(alert.dueAt)}</small>}</div><em>{alert.severity === 'critical' ? 'Crítico' : alert.severity === 'attention' ? 'Atenção' : 'Próximo'}</em></div>)}</div> : <Empty icon={FiCheck} title="Sem alertas" description="Não há nenhuma pendência automática detectada agora." />}
      </article>
      <article className="pwi-card">
        <SectionTitle eyebrow="Fluxo patrimonial" title="Receitas x despesas · 12 meses" description="A leitura considera aluguel, outras receitas, despesas do proprietário e manutenção." />
        <MiniTrend monthly={analytics.monthly || []} />
        <div className="pwi-chart-legend"><span><i className="income" /> Receita</span><span><i className="expense" /> Despesa</span></div>
      </article>
    </section>
    <section className="pwi-grid-two">
      <article className="pwi-card">
        <SectionTitle eyebrow="Patrimônio" title="Perfil financeiro e documental" action={hasPermission(permissions, 'edit') && <button className="pwi-button ghost" onClick={() => setEditProfile((v) => !v)}><FiEdit3 /> {editProfile ? 'Fechar' : 'Editar'}</button>} />
        {!editProfile ? <div className="pwi-facts"><div><small>Valor de aquisição</small><b>{profile.acquisition_value ? money(profile.acquisition_value) : 'Não informado'}</b></div><div><small>Valor de mercado</small><b>{profile.market_value ? money(profile.market_value) : 'Não informado'}</b></div><div><small>Aquisição</small><b>{date(profile.acquired_on)}</b></div><div><small>Registro / matrícula</small><b>{profile.registry_reference || 'Não informado'}</b></div><div><small>Seguro até</small><b>{date(profile.insurance_expires_on)}</b></div><div><small>Documento até</small><b>{date(profile.document_expires_on)}</b></div></div> : <form onSubmit={saveProfile} className="pwi-form-grid"><Field label="Valor de aquisição"><input type="number" step="0.01" min="0" value={form.acquisition_value || ''} onChange={(e) => setForm({ ...form, acquisition_value: e.target.value })} /></Field><Field label="Valor de mercado"><input type="number" step="0.01" min="0" value={form.market_value || ''} onChange={(e) => setForm({ ...form, market_value: e.target.value })} /></Field><Field label="Data de aquisição"><input type="date" value={form.acquired_on || ''} onChange={(e) => setForm({ ...form, acquired_on: e.target.value })} /></Field><Field label="Matrícula / referência"><input value={form.registry_reference || ''} onChange={(e) => setForm({ ...form, registry_reference: e.target.value })} /></Field><Field label="Seguro válido até"><input type="date" value={form.insurance_expires_on || ''} onChange={(e) => setForm({ ...form, insurance_expires_on: e.target.value })} /></Field><Field label="Documento válido até"><input type="date" value={form.document_expires_on || ''} onChange={(e) => setForm({ ...form, document_expires_on: e.target.value })} /></Field><div className="span-2 pwi-actions"><button className="pwi-button primary"><FiSave /> Salvar perfil</button></div></form>}
      </article>
      <article className="pwi-card">
        <SectionTitle eyebrow="Classificação" title="Tags do patrimônio" description="Facilitam busca, filtros e segmentação da carteira." />
        <div className="pwi-tag-cloud">{(tags || []).map((tag) => <span key={tag.id || tag.tag || tag}><FiTag /> {tag.tag || tag}</span>)}</div>
        {hasPermission(permissions, 'edit') && <div className="pwi-inline-input"><input value={tagText} onChange={(e) => setTagText(e.target.value)} placeholder="Mobiliado, financiado, alto padrão..." /><button className="pwi-button primary" onClick={saveTags}><FiSave /> Salvar</button></div>}
      </article>
    </section>
    {health.factors?.length > 0 && <article className="pwi-card"><SectionTitle eyebrow="Como o score foi calculado" title="Fatores que reduziram a pontuação" /><div className="pwi-factor-grid">{health.factors.map((factor) => <div key={factor.key}><strong>{factor.impact}</strong><span><b>{factor.label}</b><small>{factor.detail}</small></span></div>)}</div></article>}
  </div>;
}

function FinancialTab({ propertyId, financial, permissions, onReload, notify }) {
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ direction: 'expense', category: 'iptu', description: '', amount: '', occurred_on: today(), due_on: '', status: 'paid', recurring: false, recurrence_months: '' });
  const submit = async (e) => { e.preventDefault(); try { await appApi.post(`/assets/property/${propertyId}/financial/entries`, { ...form, amount: Number(form.amount), due_on: form.due_on || null, recurrence_months: form.recurring && form.recurrence_months ? Number(form.recurrence_months) : null }); notify('Lançamento financeiro registrado.'); setOpen(false); setForm({ direction: 'expense', category: 'iptu', description: '', amount: '', occurred_on: today(), due_on: '', status: 'paid', recurring: false, recurrence_months: '' }); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const remove = async (entry) => { if (!window.confirm(`Excluir “${entry.description}”?`)) return; try { await appApi.delete(`/assets/property/${propertyId}/financial/entries/${entry.id}`); notify('Lançamento removido.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const s = financial.summary || {};
  return <div className="pwi-tab-content">
    <SectionTitle eyebrow="Resultado real" title="Financeiro do imóvel" description="Receita de locação, entradas avulsas, despesas do proprietário e manutenção no mesmo resultado." action={hasPermission(permissions, 'financial') && <button className="pwi-button primary" onClick={() => setOpen((v) => !v)}><FiPlus /> Novo lançamento</button>} />
    <section className="pwi-metrics"><Metric label="Receita bruta · 12m" value={money(s.gross_income_12m)} /><Metric label="Despesas do proprietário" value={money(s.owner_expenses_12m)} /><Metric label="Manutenção" value={money(s.maintenance_cost_12m)} /><Metric label="Resultado líquido · 12m" value={money(s.net_result_12m)} tone={Number(s.net_result_12m) >= 0 ? 'success' : 'danger'} /><Metric label="Rentabilidade líquida" value={pct(s.net_yield_12m)} /><Metric label="Em atraso" value={money(s.overdue)} tone={Number(s.overdue) > 0 ? 'danger' : 'success'} /></section>
    {open && <form className="pwi-card pwi-form" onSubmit={submit}><div className="pwi-form-grid"><Field label="Tipo"><select value={form.direction} onChange={(e) => setForm({ ...form, direction: e.target.value })}><option value="expense">Despesa</option><option value="income">Receita</option></select></Field><Field label="Categoria"><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option value="iptu">IPTU</option><option value="condo">Condomínio</option><option value="insurance">Seguro</option><option value="renovation">Reforma</option><option value="painting">Pintura</option><option value="cleaning">Limpeza</option><option value="administration">Administração</option><option value="utility">Conta / consumo</option><option value="other_income">Outra receita</option><option value="other">Outro</option></select></Field><Field label="Descrição" span><input required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field><Field label="Valor"><input required type="number" min="0.01" step="0.01" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} /></Field><Field label="Data"><input required type="date" value={form.occurred_on} onChange={(e) => setForm({ ...form, occurred_on: e.target.value })} /></Field><Field label="Vencimento"><input type="date" value={form.due_on} onChange={(e) => setForm({ ...form, due_on: e.target.value })} /></Field><Field label="Situação"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option value="paid">Pago</option><option value="pending">Pendente</option><option value="planned">Planejado</option></select></Field><Field label="Recorrência"><div className="pwi-check-field"><input type="checkbox" checked={form.recurring} onChange={(e) => setForm({ ...form, recurring: e.target.checked })} /><span>É recorrente</span></div></Field><Field label="A cada quantos meses"><input disabled={!form.recurring} type="number" min="1" max="120" value={form.recurrence_months} onChange={(e) => setForm({ ...form, recurrence_months: e.target.value })} /></Field></div><div className="pwi-actions"><button type="button" className="pwi-button ghost" onClick={() => setOpen(false)}>Cancelar</button><button className="pwi-button primary"><FiSave /> Registrar</button></div></form>}
    <article className="pwi-card"><SectionTitle eyebrow="Fluxo mensal" title="Receitas, despesas e resultado" /><MiniTrend monthly={financial.monthly || []} /><div className="pwi-chart-legend"><span><i className="income" /> Receita</span><span><i className="expense" /> Despesa</span></div></article>
    <section className="pwi-grid-two">
      <article className="pwi-card"><SectionTitle eyebrow="Patrimônio" title="Despesas e receitas avulsas" />{financial.entries?.length ? <div className="pwi-list">{financial.entries.map((entry) => <div className="pwi-list-row" key={entry.id}><span className={`pwi-round ${entry.direction}`}><FiDollarSign /></span><div><b>{entry.description}</b><small>{date(entry.occurred_on)} · {entry.category}</small></div><strong className={entry.direction === 'expense' ? 'danger' : 'success'}>{entry.direction === 'expense' ? '− ' : '+ '}{money(entry.amount)}</strong><Badge value={entry.status} />{hasPermission(permissions, 'financial') && <button className="pwi-icon-button danger" onClick={() => remove(entry)}><FiTrash2 /></button>}</div>)}</div> : <Empty icon={FiDollarSign} title="Sem lançamentos patrimoniais" description="Registre IPTU, seguro, condomínio, reforma, limpeza e outras receitas ou despesas." />}</article>
      <article className="pwi-card"><SectionTitle eyebrow="Locações" title="Cobranças de aluguel" />{financial.charges?.length ? <div className="pwi-list">{financial.charges.slice(0, 40).map((charge) => <div className="pwi-list-row" key={charge.id}><span className="pwi-round"><FiCalendar /></span><div><b>{charge.description}</b><small>Vence {date(charge.due_date)}</small></div><strong>{money(charge.amount)}</strong><Badge value={charge.status} /></div>)}</div> : <Empty icon={FiCalendar} title="Sem cobranças" description="As cobranças das locações aparecerão aqui." />}</article>
    </section>
  </div>;
}

function LeaseTab({ data }) {
  const lease = data.current_lease; const leases = data.leases || [];
  return <div className="pwi-tab-content"><SectionTitle eyebrow="Contrato e ocupação" title="Locação do imóvel" description="Visão atual e histórico contratual." />{lease ? <article className="pwi-card pwi-lease-hero"><div className="pwi-avatar"><FiUser /></div><div><span className="pwi-eyebrow">Locação em destaque</span><h2>{lease.tenant_name}</h2><p>{lease.tenant_email || 'E-mail não informado'} {lease.tenant_phone ? ` · ${lease.tenant_phone}` : ''}</p></div><div className="pwi-lease-value"><strong>{money(lease.rent_amount)}</strong><small>vence dia {lease.due_day}</small></div><Badge value={lease.status} /></article> : <Empty icon={FiKey} title="Sem locação vigente" description="O imóvel está livre ou ainda não tem uma locação em vigência." />}
    {lease && <article className="pwi-card"><div className="pwi-facts"><div><small>Início</small><b>{date(lease.starts_on)}</b></div><div><small>Fim</small><b>{date(lease.ends_on)}</b></div><div><small>Caução</small><b>{lease.deposit_months ? `${lease.deposit_months} aluguel(is)` : 'Sem caução'}</b></div><div><small>Reajuste</small><b>{lease.adjustment_index || 'A definir'}</b></div><div><small>Frequência</small><b>{lease.adjustment_frequency_months || 12} meses</b></div><div><small>Finalidade</small><b>{lease.purpose || '—'}</b></div></div></article>}
    <article className="pwi-card"><SectionTitle eyebrow="Histórico" title="Todas as locações" />{leases.length ? <div className="pwi-table"><div className="pwi-table-head"><span>Inquilino</span><span>Período</span><span>Aluguel</span><span>Status</span></div>{leases.map((item) => <div className="pwi-table-row" key={item.id}><span><b>{item.tenant_name}</b><small>{item.tenant_email}</small></span><span>{date(item.starts_on)} → {date(item.ends_on)}</span><strong>{money(item.rent_amount)}</strong><Badge value={item.status} /></div>)}</div> : <Empty icon={FiFileText} title="Sem histórico contratual" description="As locações anteriores aparecerão aqui." />}</article>
  </div>;
}

function InspectionsTab({ propertyId, inspections, spaces, files, permissions, onReload, notify }) {
  const [open, setOpen] = useState(false); const [compare, setCompare] = useState(null); const [busy, setBusy] = useState(false);
  const [form, setForm] = useState({ type: 'periodic', occurred_at: localDateTime(), summary: '', rows: '' });
  const parseRows = () => form.rows.split('\n').map((line) => line.trim()).filter(Boolean).map((line) => { const [spaceName, label, condition = 'good', notes = ''] = line.split('|').map((x) => x.trim()); const space = spaces.find((s) => s.name.toLowerCase() === String(spaceName || '').toLowerCase()); return { space_id: space?.id || null, space_name: space?.name || spaceName || 'Geral', label: label || spaceName, condition, notes: notes || null }; });
  const submit = async (e) => { e.preventDefault(); setBusy(true); try { await appApi.post(`/assets/property/${propertyId}/inspections`, { type: form.type, occurred_at: form.occurred_at, summary: form.summary || null, items: parseRows() }); notify('Vistoria registrada.'); setOpen(false); setForm({ type: 'periodic', occurred_at: localDateTime(), summary: '', rows: '' }); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  const compareInspections = async () => { try { const { data } = await appApi.get(`/assets/property/${propertyId}/inspection-comparison`); setCompare(data); } catch (error) { notify(errorMessage(error), 'error'); } };
  const inspectionPhotos = (inspectionId) => files.filter((f) => Number(f.inspection_id) === Number(inspectionId));
  return <div className="pwi-tab-content"><SectionTitle eyebrow="Estado do patrimônio" title="Vistorias estruturadas" description="Compare ambientes e condições entre entrada, periódicas e saída." action={<div className="pwi-button-row">{inspections.length >= 2 && <button className="pwi-button ghost" onClick={compareInspections}><FiBarChart2 /> Comparar</button>}{hasPermission(permissions, 'inspections') && <button className="pwi-button primary" onClick={() => setOpen((v) => !v)}><FiPlus /> Nova vistoria</button>}</div>} />
    {open && <form className="pwi-card pwi-form" onSubmit={submit}><div className="pwi-form-grid"><Field label="Tipo"><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="entry">Entrada</option><option value="periodic">Periódica</option><option value="exit">Saída</option></select></Field><Field label="Data e hora"><input required type="datetime-local" value={form.occurred_at} onChange={(e) => setForm({ ...form, occurred_at: e.target.value })} /></Field><Field label="Resumo" span><textarea rows="3" value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} placeholder="Estado geral e observações..." /></Field><Field label="Itens — Ambiente | Item | condição | observação" span><textarea rows="7" value={form.rows} onChange={(e) => setForm({ ...form, rows: e.target.value })} placeholder={'Sala | Pintura | good | Sem marcas\nBanheiro | Torneira | fair | Pequeno desgaste'} /></Field></div><div className="pwi-hint">Condições aceitas: new, excellent, good, fair, poor, damaged ou missing. Ambientes cadastrados: {spaces.map((s) => s.name).join(', ') || 'nenhum'}.</div><div className="pwi-actions"><button type="button" className="pwi-button ghost" onClick={() => setOpen(false)}>Cancelar</button><button disabled={busy} className="pwi-button primary"><FiSave /> {busy ? 'Salvando…' : 'Registrar'}</button></div></form>}
    {compare && <article className="pwi-card pwi-comparison"><SectionTitle eyebrow="Comparação" title={`${date(compare.left?.occurred_at)} × ${date(compare.right?.occurred_at)}`} action={<button className="pwi-icon-button" onClick={() => setCompare(null)}><FiX /></button>} /><div className="pwi-compare-summary"><span><b>{compare.summary?.changed || 0}</b> alterados</span><span><b>{compare.summary?.unchanged || 0}</b> iguais</span><span><b>{compare.summary?.added || 0}</b> adicionados</span><span><b>{compare.summary?.removed || 0}</b> removidos</span></div><div className="pwi-compare-list">{compare.differences?.map((item) => <div className={item.changed ? 'changed' : ''} key={item.key}><span><small>{item.space_name}</small><b>{item.label}</b></span><span><small>Antes</small><b>{conditionLabel[item.before?.condition] || item.before?.condition || '—'}</b><em>{item.before?.notes}</em></span><FiArrowLeft className="reverse" /><span><small>Depois</small><b>{conditionLabel[item.after?.condition] || item.after?.condition || '—'}</b><em>{item.after?.notes}</em></span></div>)}</div></article>}
    {inspections.length ? <div className="pwi-timeline">{inspections.map((inspection) => <article key={inspection.id}><span><FiCamera /></span><div><header><div><b>Vistoria de {inspection.type === 'entry' ? 'entrada' : inspection.type === 'exit' ? 'saída' : 'periódica'}</b><small>{dateTime(inspection.occurred_at)}</small></div><em>{inspection.items?.length || 0} itens · {inspectionPhotos(inspection.id).length} foto(s)</em></header><p>{inspection.summary || 'Sem resumo.'}</p>{inspection.items?.length > 0 && <div className="pwi-inspection-items">{inspection.items.slice(0, 12).map((item, idx) => <span key={idx}><b>{item.space_name || 'Geral'} · {item.label || item.name}</b><small>{conditionLabel[item.condition] || item.condition || '—'} {item.notes ? ` · ${item.notes}` : ''}</small></span>)}</div>}</div></article>)}</div> : <Empty icon={FiCamera} title="Nenhuma vistoria" description="Registre a condição do imóvel para construir o histórico comparativo." />}
  </div>;
}

function FilesTab({ propertyId, files, spaces, inspections, maintenance, permissions, onReload, notify }) {
  const inputRef = useRef(null); const [busy, setBusy] = useState(false); const [filter, setFilter] = useState('all'); const [previews, setPreviews] = useState({});
  const [meta, setMeta] = useState({ group: 'photos', context: 'general', occurred_on: today(), space_id: '', inspection_id: '', maintenance_id: '', before_after: '', document_type: '', caption: '' });
  useEffect(() => { let active = true; const urls = []; Promise.all(files.filter((f) => String(f.mime_type || '').startsWith('image/')).map(async (f) => { try { const r = await appApi.get(`/assets/property/${propertyId}/files/${f.id}`, { responseType: 'blob' }); const u = URL.createObjectURL(r.data); urls.push(u); return [f.id, u]; } catch { return [f.id, null]; } })).then((pairs) => active && setPreviews(Object.fromEntries(pairs.filter(([, u]) => u)))); return () => { active = false; urls.forEach(URL.revokeObjectURL); }; }, [files, propertyId]);
  const upload = async (e) => { const selected = [...(e.target.files || [])]; if (!selected.length) return; setBusy(true); try { for (const file of selected) { const fd = new FormData(); fd.append('file', file); Object.entries(meta).forEach(([k, v]) => { if (v !== '' && v !== null) fd.append(k, v); }); await appApi.post(`/assets/property/${propertyId}/files`, fd); } notify(`${selected.length} arquivo(s) adicionado(s).`); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); e.target.value = ''; } };
  const download = async (file) => { try { const r = await appApi.get(`/assets/property/${propertyId}/files/${file.id}`, { responseType: 'blob' }); const url = URL.createObjectURL(r.data); const a = document.createElement('a'); a.href = url; a.download = file.original_name || 'arquivo'; a.click(); URL.revokeObjectURL(url); } catch (error) { notify(errorMessage(error), 'error'); } };
  const remove = async (file) => { if (!window.confirm(`Excluir “${file.original_name}”?`)) return; try { await appApi.delete(`/assets/property/${propertyId}/files/${file.id}`); notify('Arquivo removido.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const primary = async (file) => { try { await appApi.patch(`/assets/property/${propertyId}/files/${file.id}`, { is_primary: true }); notify('Foto definida como capa.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const filtered = files.filter((f) => filter === 'all' || f.context === filter || f.group === filter);
  return <div className="pwi-tab-content"><SectionTitle eyebrow="Histórico visual e documental" title="Acervo do imóvel" description="Fotos por contexto/data e documentos que pertencem ao patrimônio independentemente da locação." action={hasPermission(permissions, 'files') && <button className="pwi-button primary" disabled={busy} onClick={() => inputRef.current?.click()}><FiUpload /> {busy ? 'Enviando…' : 'Adicionar'}</button>} />
    {hasPermission(permissions, 'files') && <article className="pwi-card pwi-upload-config"><div className="pwi-form-grid"><Field label="Grupo"><select value={meta.group} onChange={(e) => setMeta({ ...meta, group: e.target.value })}><option value="photos">Fotos</option><option value="documents">Documentos</option><option value="other">Outros</option></select></Field><Field label="Contexto"><select value={meta.context} onChange={(e) => setMeta({ ...meta, context: e.target.value })}>{Object.entries(fileContextLabel).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="Data"><input type="date" value={meta.occurred_on} onChange={(e) => setMeta({ ...meta, occurred_on: e.target.value })} /></Field><Field label="Ambiente"><select value={meta.space_id} onChange={(e) => setMeta({ ...meta, space_id: e.target.value })}><option value="">Geral</option>{spaces.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Vistoria"><select value={meta.inspection_id} onChange={(e) => setMeta({ ...meta, inspection_id: e.target.value })}><option value="">Nenhuma</option>{inspections.map((i) => <option key={i.id} value={i.id}>{date(i.occurred_at)} · {i.type}</option>)}</select></Field><Field label="Manutenção"><select value={meta.maintenance_id} onChange={(e) => setMeta({ ...meta, maintenance_id: e.target.value })}><option value="">Nenhuma</option>{maintenance.map((m) => <option key={m.id} value={m.id}>{m.title}</option>)}</select></Field><Field label="Antes / depois"><select value={meta.before_after} onChange={(e) => setMeta({ ...meta, before_after: e.target.value })}><option value="">Não se aplica</option><option value="before">Antes</option><option value="after">Depois</option></select></Field><Field label="Tipo do documento"><input value={meta.document_type} onChange={(e) => setMeta({ ...meta, document_type: e.target.value })} placeholder="Matrícula, IPTU, seguro..." /></Field><Field label="Legenda" span><input value={meta.caption} onChange={(e) => setMeta({ ...meta, caption: e.target.value })} /></Field></div><input ref={inputRef} hidden multiple type="file" onChange={upload} accept="image/*,.pdf,.txt,.csv,.doc,.docx,.xls,.xlsx,.zip" /></article>}
    <div className="pwi-filter-chips"><button className={filter === 'all' ? 'active' : ''} onClick={() => setFilter('all')}>Tudo</button><button className={filter === 'photos' ? 'active' : ''} onClick={() => setFilter('photos')}>Fotos</button><button className={filter === 'documents' ? 'active' : ''} onClick={() => setFilter('documents')}>Documentos</button>{Object.entries(fileContextLabel).map(([v, l]) => <button className={filter === v ? 'active' : ''} key={v} onClick={() => setFilter(v)}>{l}</button>)}</div>
    {filtered.length ? <div className="pwi-file-gallery">{filtered.map((file) => <article className={String(file.mime_type || '').startsWith('image/') ? 'image' : 'document'} key={file.id}>{previews[file.id] ? <img src={previews[file.id]} alt={file.caption || file.original_name} /> : <span className="pwi-file-icon"><FiFileText /></span>}{file.is_primary && <em className="pwi-cover">Capa</em>}<div><small>{fileContextLabel[file.context] || file.context || file.group}</small><b>{file.caption || file.original_name}</b><p>{file.occurred_on ? date(file.occurred_on) : date(file.created_at)} · {bytes(file.file_size)}</p><div className="pwi-button-row">{String(file.mime_type || '').startsWith('image/') && !file.is_primary && hasPermission(permissions, 'files') && <button onClick={() => primary(file)}>Capa</button>}<button onClick={() => download(file)}><FiDownload /></button>{hasPermission(permissions, 'files') && <button className="danger" onClick={() => remove(file)}><FiTrash2 /></button>}</div></div></article>)}</div> : <Empty icon={FiUpload} title="Nenhum arquivo neste filtro" description="Adicione fotos, documentos e evidências do patrimônio." />}
  </div>;
}

function MaintenanceTab({ propertyId, maintenance, preventive, spaces, permissions, onReload, notify }) {
  const [mode, setMode] = useState(null); const [form, setForm] = useState({ title: '', description: '', priority: 'normal', due_at: '', vendor: '', estimated_cost: '', space_id: '' });
  const [plan, setPlan] = useState({ title: '', description: '', priority: 'normal', frequency_months: 12, next_due_on: today(), estimated_cost: '', space_id: '' });
  const addMaintenance = async (e) => { e.preventDefault(); try { await appApi.post(`/assets/property/${propertyId}/maintenance`, { ...form, space_id: form.space_id ? Number(form.space_id) : null, due_at: form.due_at || null, estimated_cost: form.estimated_cost || null }); notify('Manutenção registrada.'); setMode(null); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const addPlan = async (e) => { e.preventDefault(); try { await appApi.post(`/assets/property/${propertyId}/preventive`, { ...plan, space_id: plan.space_id ? Number(plan.space_id) : null, frequency_months: Number(plan.frequency_months), estimated_cost: plan.estimated_cost || null }); notify('Plano preventivo criado.'); setMode(null); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const status = async (item, next) => { try { await appApi.patch(`/assets/property/${propertyId}/maintenance/${item.id}`, { status: next }); notify('Manutenção atualizada.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const completePlan = async (item) => { const raw = window.prompt('Custo real da manutenção (opcional):', item.estimated_cost || ''); if (raw === null) return; try { await appApi.post(`/assets/property/${propertyId}/preventive/${item.id}/complete`, { completed_on: today(), actual_cost: raw === '' ? null : Number(raw) }); notify('Preventiva concluída e próxima execução recalculada.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  return <div className="pwi-tab-content"><SectionTitle eyebrow="Conservação" title="Manutenção corretiva e preventiva" description="Ocorrências atuais e rotinas programadas no mesmo fluxo operacional." action={hasPermission(permissions, 'maintenance') && <div className="pwi-button-row"><button className="pwi-button ghost" onClick={() => setMode(mode === 'preventive' ? null : 'preventive')}><FiCalendar /> Nova preventiva</button><button className="pwi-button primary" onClick={() => setMode(mode === 'maintenance' ? null : 'maintenance')}><FiPlus /> Nova manutenção</button></div>} />
    {mode === 'maintenance' && <form className="pwi-card pwi-form" onSubmit={addMaintenance}><div className="pwi-form-grid"><Field label="Título" span><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /></Field><Field label="Prioridade"><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}>{Object.entries(priorityLabel).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="Ambiente"><select value={form.space_id} onChange={(e) => setForm({ ...form, space_id: e.target.value })}><option value="">Geral</option>{spaces.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Prazo"><input type="datetime-local" value={form.due_at} onChange={(e) => setForm({ ...form, due_at: e.target.value })} /></Field><Field label="Prestador"><input value={form.vendor} onChange={(e) => setForm({ ...form, vendor: e.target.value })} /></Field><Field label="Custo estimado"><input type="number" min="0" step="0.01" value={form.estimated_cost} onChange={(e) => setForm({ ...form, estimated_cost: e.target.value })} /></Field><Field label="Descrição" span><textarea rows="4" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></Field></div><div className="pwi-actions"><button className="pwi-button primary"><FiSave /> Registrar</button></div></form>}
    {mode === 'preventive' && <form className="pwi-card pwi-form" onSubmit={addPlan}><div className="pwi-form-grid"><Field label="Rotina" span><input required value={plan.title} onChange={(e) => setPlan({ ...plan, title: e.target.value })} placeholder="Ex.: Limpeza da caixa d’água" /></Field><Field label="Ambiente"><select value={plan.space_id} onChange={(e) => setPlan({ ...plan, space_id: e.target.value })}><option value="">Geral</option>{spaces.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Prioridade"><select value={plan.priority} onChange={(e) => setPlan({ ...plan, priority: e.target.value })}>{Object.entries(priorityLabel).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="Frequência (meses)"><input required type="number" min="1" max="120" value={plan.frequency_months} onChange={(e) => setPlan({ ...plan, frequency_months: e.target.value })} /></Field><Field label="Próxima execução"><input required type="date" value={plan.next_due_on} onChange={(e) => setPlan({ ...plan, next_due_on: e.target.value })} /></Field><Field label="Custo estimado"><input type="number" min="0" step="0.01" value={plan.estimated_cost} onChange={(e) => setPlan({ ...plan, estimated_cost: e.target.value })} /></Field><Field label="Descrição" span><textarea rows="3" value={plan.description} onChange={(e) => setPlan({ ...plan, description: e.target.value })} /></Field></div><div className="pwi-actions"><button className="pwi-button primary"><FiSave /> Criar rotina</button></div></form>}
    <section className="pwi-grid-two"><article className="pwi-card"><SectionTitle eyebrow="Corretiva" title="Ocorrências e reparos" />{maintenance.length ? <div className="pwi-maintenance-list">{maintenance.map((item) => <div className={`pwi-maintenance-item ${item.priority}`} key={item.id}><header><div><Badge value={item.priority} priority /><Badge value={item.status} /></div><b>{item.title}</b></header><p>{item.description || 'Sem descrição.'}</p><div className="pwi-meta-row"><span><FiCalendar /> {item.due_at ? dateTime(item.due_at) : 'Sem prazo'}</span><span><FiDollarSign /> {item.actual_cost !== null ? money(item.actual_cost) : item.estimated_cost !== null ? `${money(item.estimated_cost)} estimado` : 'Custo a definir'}</span></div>{hasPermission(permissions, 'maintenance') && <select value={item.status} onChange={(e) => status(item, e.target.value)}><option value="open">Aberta</option><option value="in_progress">Em andamento</option><option value="waiting">Aguardando</option><option value="completed">Concluída</option><option value="cancelled">Cancelada</option></select>}</div>)}</div> : <Empty icon={FiCheck} title="Sem manutenção corretiva" description="Nenhuma ocorrência foi registrada." />}</article>
      <article className="pwi-card"><SectionTitle eyebrow="Preventiva" title="Rotinas programadas" />{preventive.length ? <div className="pwi-maintenance-list">{preventive.map((item) => <div className={`pwi-maintenance-item ${item.days_until_due < 0 ? 'urgent' : item.priority}`} key={item.id}><header><div><Badge value={item.priority} priority />{item.days_until_due < 0 && <span className="pwi-badge status-critical">Vencida</span>}</div><b>{item.title}</b></header><p>{item.description || `Executar a cada ${item.frequency_months} meses.`}</p><div className="pwi-meta-row"><span><FiCalendar /> Próxima: {date(item.next_due_on)}</span><span><FiDollarSign /> {item.estimated_cost !== null ? money(item.estimated_cost) : 'Sem estimativa'}</span></div>{hasPermission(permissions, 'preventive') && <button className="pwi-button ghost full" onClick={() => completePlan(item)}><FiCheck /> Marcar concluída</button>}</div>)}</div> : <Empty icon={FiCalendar} title="Sem manutenção preventiva" description="Cadastre rotinas para o sistema antecipar as tarefas automaticamente." />}</article></section>
  </div>;
}

function StructureTab({ propertyId, spaces, inventory, permissions, onReload, notify }) {
  const [spaceName, setSpaceName] = useState(''); const [spaceType, setSpaceType] = useState('room');
  const [item, setItem] = useState({ name: '', category: 'furniture', condition: 'good', quantity: 1, space_id: '', serial_number: '', acquisition_value: '' });
  const addSpace = async (e) => { e.preventDefault(); try { await appApi.post(`/assets/property/${propertyId}/spaces`, { name: spaceName, type: spaceType }); setSpaceName(''); notify('Ambiente cadastrado.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const addItem = async (e) => { e.preventDefault(); try { await appApi.post(`/assets/property/${propertyId}/inventory`, { ...item, space_id: item.space_id ? Number(item.space_id) : null, quantity: Number(item.quantity), acquisition_value: item.acquisition_value || null }); setItem({ name: '', category: 'furniture', condition: 'good', quantity: 1, space_id: '', serial_number: '', acquisition_value: '' }); notify('Item adicionado ao inventário.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const removeSpace = async (space) => { if (!window.confirm(`Remover ambiente “${space.name}”? Itens ficarão sem ambiente.`)) return; try { await appApi.delete(`/assets/property/${propertyId}/spaces/${space.id}`); notify('Ambiente removido.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const removeItem = async (row) => { if (!window.confirm(`Remover “${row.name}” do inventário?`)) return; try { await appApi.delete(`/assets/property/${propertyId}/inventory/${row.id}`); notify('Item removido.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const grouped = spaces.map((space) => ({ ...space, items: inventory.filter((i) => Number(i.space_id) === Number(space.id)) }));
  return <div className="pwi-tab-content"><SectionTitle eyebrow="Estrutura física" title="Ambientes e inventário" description="Cadastre os cômodos e o que existe em cada um para integrar vistorias, fotos e manutenção." />
    {hasPermission(permissions, 'edit') && <section className="pwi-grid-two"><form className="pwi-card pwi-compact-form" onSubmit={addSpace}><h3>Novo ambiente</h3><input required value={spaceName} onChange={(e) => setSpaceName(e.target.value)} placeholder="Sala, Cozinha, Quarto 1..." /><select value={spaceType} onChange={(e) => setSpaceType(e.target.value)}><option value="room">Cômodo</option><option value="bathroom">Banheiro</option><option value="kitchen">Cozinha</option><option value="external">Área externa</option><option value="garage">Garagem</option><option value="storage">Depósito</option><option value="other">Outro</option></select><button className="pwi-button primary"><FiPlus /> Adicionar ambiente</button></form>
      {hasPermission(permissions, 'inventory') && <form className="pwi-card pwi-compact-form" onSubmit={addItem}><h3>Novo item de inventário</h3><input required value={item.name} onChange={(e) => setItem({ ...item, name: e.target.value })} placeholder="Geladeira, armário, ar-condicionado..." /><select value={item.space_id} onChange={(e) => setItem({ ...item, space_id: e.target.value })}><option value="">Sem ambiente</option>{spaces.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><div className="pwi-inline-two"><select value={item.condition} onChange={(e) => setItem({ ...item, condition: e.target.value })}>{Object.entries(conditionLabel).filter(([v]) => ['new','excellent','good','fair','poor','damaged','missing'].includes(v)).map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select><input type="number" min="1" value={item.quantity} onChange={(e) => setItem({ ...item, quantity: e.target.value })} placeholder="Qtd." /></div><input value={item.serial_number} onChange={(e) => setItem({ ...item, serial_number: e.target.value })} placeholder="Número de série (opcional)" /><button className="pwi-button primary"><FiBox /> Adicionar item</button></form>}</section>}
    <div className="pwi-room-grid">{grouped.map((space) => <article className="pwi-card pwi-room" key={space.id}><header><div><span className="pwi-round"><FiHome /></span><div><h3>{space.name}</h3><small>{space.type} · {space.items.length} item(ns)</small></div></div>{hasPermission(permissions, 'edit') && <button className="pwi-icon-button danger" onClick={() => removeSpace(space)}><FiTrash2 /></button>}</header>{space.items.length ? <div className="pwi-inventory-list">{space.items.map((row) => <div key={row.id}><span><b>{row.name}</b><small>{row.quantity} un. {row.serial_number ? `· ${row.serial_number}` : ''}</small></span><Badge value={row.condition} />{hasPermission(permissions, 'inventory') && <button className="pwi-icon-button danger" onClick={() => removeItem(row)}><FiTrash2 /></button>}</div>)}</div> : <p className="pwi-muted">Nenhum item neste ambiente.</p>}</article>)}</div>
    {spaces.length === 0 && <Empty icon={FiLayers} title="Nenhum ambiente estruturado" description="Comece cadastrando Sala, Cozinha, Quartos, Banheiros e áreas externas." />}
  </div>;
}

function AccessTab({ propertyId, ownerships, shares, permissions, onReload, notify }) {
  const [owner, setOwner] = useState({ email: '', role: 'co_owner', share_percent: 0 });
  const [share, setShare] = useState({ grantee_email: '', role: 'viewer', expires_at: futureDateTime(7), permissions: ['view', 'report'] });
  const [lastLink, setLastLink] = useState('');
  const addOwner = async (e) => { e.preventDefault(); try { await appApi.post(`/assets/property/${propertyId}/ownerships`, { email: owner.email, role: owner.role, share_percent: Number(owner.share_percent) }); notify('Participação adicionada.'); setOwner({ email: '', role: 'co_owner', share_percent: 0 }); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const deleteOwner = async (row) => { if (!window.confirm(`Remover ${row.display_name || row.email}?`)) return; try { await appApi.delete(`/assets/property/${propertyId}/ownerships/${row.id}`); notify('Participação removida.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const createShare = async (e) => { e.preventDefault(); try { const { data } = await appApi.post(`/assets/property/${propertyId}/shares`, share); const link = `${window.location.origin}/share/${data.token}`; setLastLink(link); await navigator.clipboard?.writeText(link).catch(() => {}); notify('Link temporário criado e copiado.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const revoke = async (row) => { try { await appApi.delete(`/assets/property/${propertyId}/shares/${row.id}`); notify('Acesso revogado.'); await onReload(); } catch (error) { notify(errorMessage(error), 'error'); } };
  const togglePermission = (p) => setShare((current) => ({ ...current, permissions: current.permissions.includes(p) ? current.permissions.filter((x) => x !== p) : [...current.permissions, p] }));
  return <div className="pwi-tab-content"><SectionTitle eyebrow="Governança" title="Proprietários, papéis e compartilhamentos" description="Cada pessoa vê e altera apenas o que sua função permite naquele patrimônio." />
    <section className="pwi-grid-two"><article className="pwi-card"><SectionTitle eyebrow="Copropriedade" title="Composição patrimonial" />{ownerships.length ? <div className="pwi-owner-list">{ownerships.map((row) => <div key={row.id}><span className="pwi-avatar"><FiUser /></span><div><b>{row.display_name || row.email}</b><small>{row.email} · {roleLabel[row.role] || row.role}</small></div><strong>{Number(row.share_percent).toFixed(2).replace('.', ',')}%</strong>{!row.is_primary && hasPermission(permissions, 'owners') && <button className="pwi-icon-button danger" onClick={() => deleteOwner(row)}><FiTrash2 /></button>}</div>)}</div> : <Empty icon={FiUsers} title="Sem composição" description="O proprietário principal será incluído automaticamente." />}{hasPermission(permissions, 'owners') && <form className="pwi-compact-form pwi-owner-form" onSubmit={addOwner}><input required type="email" placeholder="E-mail da conta Peter Tecnet" value={owner.email} onChange={(e) => setOwner({ ...owner, email: e.target.value })} /><select value={owner.role} onChange={(e) => setOwner({ ...owner, role: e.target.value })}><option value="co_owner">Coproprietário</option><option value="manager">Gerente</option><option value="accountant">Contador</option><option value="lawyer">Advogado</option><option value="realtor">Corretor</option></select><input type="number" min="0" max="100" step="0.01" value={owner.share_percent} onChange={(e) => setOwner({ ...owner, share_percent: e.target.value })} placeholder="Participação %" /><button className="pwi-button primary"><FiPlus /> Vincular</button></form>}</article>
      <article className="pwi-card"><SectionTitle eyebrow="Acesso temporário" title="Compartilhar com segurança" description="Ideal para contador, advogado, corretor ou prestador sem entregar acesso completo à conta." />{hasPermission(permissions, 'share') && <form className="pwi-compact-form" onSubmit={createShare}><input required type="email" placeholder="E-mail do convidado" value={share.grantee_email} onChange={(e) => setShare({ ...share, grantee_email: e.target.value })} /><select value={share.role} onChange={(e) => setShare({ ...share, role: e.target.value })}><option value="viewer">Visualizador</option><option value="accountant">Contador</option><option value="lawyer">Advogado</option><option value="realtor">Corretor</option><option value="provider">Prestador</option><option value="manager">Gerente</option></select><input required type="datetime-local" value={share.expires_at} onChange={(e) => setShare({ ...share, expires_at: e.target.value })} /><div className="pwi-permission-grid">{['financial','files','inspections','maintenance','inventory','report'].map((p) => <label key={p}><input type="checkbox" checked={share.permissions.includes(p)} onChange={() => togglePermission(p)} /> {p}</label>)}</div><button className="pwi-button primary"><FiLink /> Criar link temporário</button></form>}{lastLink && <div className="pwi-share-link"><input readOnly value={lastLink} /><button onClick={() => navigator.clipboard?.writeText(lastLink)}><FiLink /></button></div>}</article></section>
    <article className="pwi-card"><SectionTitle eyebrow="Compartilhamentos emitidos" title="Acessos temporários" />{shares.length ? <div className="pwi-table"><div className="pwi-table-head"><span>Destinatário</span><span>Papel</span><span>Expira</span><span>Status</span></div>{shares.map((row) => <div className="pwi-table-row" key={row.id}><span><b>{row.display_name || row.grantee_email}</b><small>{row.access_count || 0} acesso(s)</small></span><span>{roleLabel[row.role] || row.role}</span><span>{dateTime(row.expires_at)}</span><span>{row.active ? <Badge value="active" /> : <Badge value="cancelled" />}{row.active && hasPermission(permissions, 'share') && <button className="pwi-button tiny danger" onClick={() => revoke(row)}>Revogar</button>}</span></div>)}</div> : <Empty icon={FiShield} title="Nenhum acesso temporário" description="Crie links com prazo e escopo controlados." />}</article>
  </div>;
}

function HistoryTab({ timeline, audit }) {
  const combined = [...timeline.map((e) => ({ ...e, source: 'timeline' })), ...audit.map((e) => ({ type: `audit_${e.event_type}`, title: e.title, description: e.description, at: e.occurred_at, source: 'audit', actor_name: e.actor_name, before: e.before, after: e.after }))].sort((a, b) => new Date(b.at || 0) - new Date(a.at || 0));
  const icon = (type = '') => type.includes('financial') || type.includes('payment') ? FiDollarSign : type.includes('inspection') ? FiCamera : type.includes('file') ? FiFileText : type.includes('maintenance') || type.includes('operation') ? FiTool : type.includes('owner') || type.includes('share') ? FiUsers : FiClock;
  return <div className="pwi-tab-content"><SectionTitle eyebrow="Auditoria patrimonial" title="Linha do tempo completa" description="Alterações cadastrais, finanças, pagamentos, vistorias, manutenção, arquivos, acessos e demais eventos." />{combined.length ? <div className="pwi-timeline">{combined.map((event, index) => { const Icon = icon(event.type); const before = event.before || {}; const after = event.after || {}; const changedKeys = Object.keys(after).filter((k) => before[k] !== undefined && JSON.stringify(before[k]) !== JSON.stringify(after[k])).slice(0, 5); return <article key={`${event.source}-${event.type}-${event.at}-${index}`}><span><Icon /></span><div><header><div><b>{event.title}</b><small>{dateTime(event.at)}{event.actor_name ? ` · ${event.actor_name}` : ''}</small></div>{event.source === 'audit' && <em>Auditoria</em>}</header>{event.description && <p>{event.description}</p>}{changedKeys.length > 0 && <div className="pwi-change-list">{changedKeys.map((k) => <span key={k}><b>{k}</b><small>{String(before[k] ?? '—')} → {String(after[k] ?? '—')}</small></span>)}</div>}</div></article>; })}</div> : <Empty icon={FiClock} title="Histórico vazio" description="Os eventos aparecerão automaticamente conforme o patrimônio for administrado." />}</div>;
}

export default function PropertyWorkspaceV2() {
  const [propertyId, setPropertyId] = useState(null); const [tab, setTab] = useState('overview'); const [loading, setLoading] = useState(false); const [toast, setToast] = useState(null); const [error, setError] = useState('');
  const [data, setData] = useState(null); const [analytics, setAnalytics] = useState({}); const [financial, setFinancial] = useState({ summary: {}, entries: [], charges: [], monthly: [] });
  const [spaces, setSpaces] = useState([]); const [inventory, setInventory] = useState([]); const [preventive, setPreventive] = useState([]); const [files, setFiles] = useState([]); const [maintenance, setMaintenance] = useState([]); const [inspections, setInspections] = useState([]); const [timeline, setTimeline] = useState([]); const [tags, setTags] = useState([]); const [ownerships, setOwnerships] = useState([]); const [shares, setShares] = useState([]); const [audit, setAudit] = useState([]);
  const notify = useCallback((message, type = 'success') => { setToast({ message, type }); window.clearTimeout(window.__pwiToast); window.__pwiToast = window.setTimeout(() => setToast(null), 3500); }, []);
  const safe = async (request, fallback) => { try { const response = await request; return response.data; } catch (error) { if (![401,403,404].includes(error?.response?.status)) console.warn(error); return fallback; } };
  const load = useCallback(async (id = propertyId) => { if (!id) return; setLoading(true); setError(''); try {
    const base = await appApi.get(`/assets/property/${id}`); const nextData = base.data; const permissions = nextData.permissions || nextData.property?.permissions || [];
    const canFinancial = hasPermission(permissions, 'financial'); const canOwners = hasPermission(permissions, 'owners'); const canShare = hasPermission(permissions, 'share'); const canAudit = hasPermission(permissions, 'audit');
    const [a, f, sp, inv, prev, fi, maint, insp, time, tg, own, sh, au] = await Promise.all([
      safe(appApi.get(`/assets/property/${id}/analytics`), {}), canFinancial ? safe(appApi.get(`/assets/property/${id}/financial`), { summary: {}, entries: [], charges: [], monthly: [] }) : Promise.resolve({ summary: {}, entries: [], charges: [], monthly: [] }),
      safe(appApi.get(`/assets/property/${id}/spaces`), { items: [] }), safe(appApi.get(`/assets/property/${id}/inventory`), { items: [] }), safe(appApi.get(`/assets/property/${id}/preventive`), { items: [] }),
      safe(appApi.get(`/assets/property/${id}/files`), { items: [] }), safe(appApi.get(`/assets/property/${id}/maintenance`), { items: [] }), safe(appApi.get(`/assets/property/${id}/inspections`), { items: [] }), safe(appApi.get(`/assets/property/${id}/timeline`), { events: [] }), safe(appApi.get(`/assets/property/${id}/tags`), { items: [] }),
      canOwners ? safe(appApi.get(`/assets/property/${id}/ownerships`), { items: [] }) : Promise.resolve({ items: [] }), canShare ? safe(appApi.get(`/assets/property/${id}/shares`), { items: [] }) : Promise.resolve({ items: [] }), canAudit ? safe(appApi.get(`/assets/property/${id}/audit`), { items: [] }) : Promise.resolve({ items: [] }),
    ]);
    setData(nextData); setAnalytics({ ...a, monthly: f.monthly || [] }); setFinancial(f); setSpaces(sp.items || []); setInventory(inv.items || []); setPreventive(prev.items || []); setFiles(fi.items || []); setMaintenance(maint.items || []); setInspections(insp.items || []); setTimeline(time.events || []); setTags(tg.items || []); setOwnerships(own.items || []); setShares(sh.items || []); setAudit(au.items || []);
  } catch (err) { setError(errorMessage(err, 'Não foi possível carregar a gestão do imóvel.')); } finally { setLoading(false); } }, [propertyId]);
  useEffect(() => { const listener = (event) => { const id = Number(event.detail?.propertyId); if (!id) return; setPropertyId(id); setTab(event.detail?.tab || 'overview'); }; window.addEventListener('locaio:open-property', listener); return () => window.removeEventListener('locaio:open-property', listener); }, []);
  useEffect(() => { if (propertyId) load(propertyId); }, [propertyId, load]);
  useEffect(() => { if (!propertyId) return undefined; const old = document.body.style.overflow; document.body.style.overflow = 'hidden'; const key = (e) => { if (e.key === 'Escape') setPropertyId(null); }; window.addEventListener('keydown', key); return () => { document.body.style.overflow = old; window.removeEventListener('keydown', key); }; }, [propertyId]);
  const property = data?.property || data?.asset; const profile = data?.profile || {}; const alerts = data?.alerts || []; const permissions = data?.permissions || property?.permissions || [];
  const address = useMemo(() => property ? [property.street && `${property.street}${property.number ? `, ${property.number}` : ''}`, property.neighborhood, property.city && property.state ? `${property.city}/${property.state}` : property.city].filter(Boolean).join(' · ') : '', [property]);
  const report = async () => { try { notify('Gerando dossiê PDF…', 'info'); const r = await appApi.get(`/assets/property/${propertyId}/report.pdf`, { responseType: 'blob' }); const url = URL.createObjectURL(r.data); const a = document.createElement('a'); a.href = url; a.download = `dossie-${String(property?.name || propertyId).toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`; a.click(); URL.revokeObjectURL(url); notify('Dossiê gerado.'); } catch (err) { notify(errorMessage(err), 'error'); } };
  const editProperty = () => { setPropertyId(null); window.setTimeout(() => { const card = document.querySelector(`.pt-property-card[data-property-id="${propertyId}"]`); [...(card?.querySelectorAll('button') || [])].find((b) => b.textContent.toLowerCase().includes('editar'))?.click(); }, 100); };
  const createLease = () => { setPropertyId(null); window.setTimeout(() => { const card = document.querySelector(`.pt-property-card[data-property-id="${propertyId}"]`); [...(card?.querySelectorAll('button') || [])].find((b) => b.textContent.toLowerCase().includes('criar locação'))?.click(); }, 100); };
  if (!propertyId) return null;
  return <div className="pwi-shell" role="dialog" aria-modal="true" aria-label="Inteligência e gestão do imóvel">
    {toast && <div className={`pwi-toast ${toast.type}`}>{toast.message}</div>}
    <header className="pwi-topbar"><button className="pwi-back" onClick={() => setPropertyId(null)}><FiArrowLeft /> Imóveis</button>{property && <div className="pwi-title"><span className="pwi-property-icon"><FiHome /></span><div><small>Patrimônio #{property.id}</small><h1>{property.name}</h1><p><FiMapPin /> {address}</p></div></div>}<div className="pwi-top-actions">{property && <Badge value={property.status} />}<button className="pwi-icon-button" disabled={loading} onClick={() => load()} title="Atualizar"><FiRefreshCw className={loading ? 'spin' : ''} /></button>{hasPermission(permissions, 'report') && <button className="pwi-button ghost" onClick={report}><FiDownload /> PDF</button>}{hasPermission(permissions, 'edit') && <button className="pwi-button primary" onClick={editProperty}><FiEdit3 /> Editar</button>}</div></header>
    {property && <div className="pwi-quick-actions"><span>Ações rápidas</span>{property.status === 'available' && hasPermission(permissions, 'edit') && <button onClick={createLease}><FiKey /> Criar locação</button>}<button onClick={() => setTab('inspections')}><FiCamera /> Nova vistoria</button><button onClick={() => setTab('maintenance')}><FiTool /> Manutenção</button><button onClick={() => setTab('files')}><FiUpload /> Arquivo</button>{hasPermission(permissions, 'financial') && <button onClick={() => setTab('financial')}><FiDollarSign /> Lançamento</button>}{hasPermission(permissions, 'share') && <button onClick={() => setTab('access')}><FiLink /> Compartilhar</button>}</div>}
    <nav className="pwi-tabs">{tabs.filter(([key]) => key !== 'financial' || hasPermission(permissions, 'financial')).filter(([key]) => key !== 'access' || hasPermission(permissions, 'owners') || hasPermission(permissions, 'share')).map(([key, Icon, label]) => <button key={key} className={tab === key ? 'active' : ''} onClick={() => setTab(key)}><Icon /><span>{label}</span></button>)}</nav>
    <main className="pwi-main">{loading && !data ? <div className="pwi-loading"><FiRefreshCw className="spin" /><b>Carregando patrimônio…</b></div> : error ? <Empty icon={FiAlertTriangle} title="Não foi possível abrir o imóvel" description={error} action={<button className="pwi-button primary" onClick={() => load()}>Tentar novamente</button>} /> : data && <>
      {tab === 'overview' && <OverviewTab data={data} profile={profile} analytics={analytics} alerts={alerts} tags={tags} permissions={permissions} onReload={load} notify={notify} />}
      {tab === 'financial' && <FinancialTab propertyId={propertyId} financial={financial} permissions={permissions} onReload={load} notify={notify} />}
      {tab === 'lease' && <LeaseTab data={data} />}
      {tab === 'inspections' && <InspectionsTab propertyId={propertyId} inspections={inspections} spaces={spaces} files={files} permissions={permissions} onReload={load} notify={notify} />}
      {tab === 'files' && <FilesTab propertyId={propertyId} files={files} spaces={spaces} inspections={inspections} maintenance={maintenance} permissions={permissions} onReload={load} notify={notify} />}
      {tab === 'maintenance' && <MaintenanceTab propertyId={propertyId} maintenance={maintenance} preventive={preventive} spaces={spaces} permissions={permissions} onReload={load} notify={notify} />}
      {tab === 'structure' && <StructureTab propertyId={propertyId} spaces={spaces} inventory={inventory} permissions={permissions} onReload={load} notify={notify} />}
      {tab === 'access' && <AccessTab propertyId={propertyId} ownerships={ownerships} shares={shares} permissions={permissions} onReload={load} notify={notify} />}
      {tab === 'history' && <HistoryTab timeline={timeline} audit={audit} />}
    </>}</main>
  </div>;
}
