import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
  FiAlertCircle, FiArrowLeft, FiBriefcase, FiCalendar, FiCheck, FiChevronRight, FiCreditCard,
  FiDollarSign, FiDownload, FiEye, FiEyeOff, FiFileText, FiHome, FiKey, FiLogOut, FiMail,
  FiMapPin, FiPlus, FiRefreshCw, FiSend, FiShield, FiTrash2, FiUpload, FiUser,
} from 'react-icons/fi';
import api, { appApi, errorMessage, storeSession } from './services/api.js';
import {
  ConfirmDialog, Donut, EmptyState, MetricCard, MiniBars, Modal, PageHeader, Skeleton, StatusBadge,
} from './components/ui-kit.jsx';

const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0));
const date = (value) => value ? new Intl.DateTimeFormat('pt-BR', { timeZone: 'UTC' }).format(new Date(`${String(value).slice(0, 10)}T12:00:00Z`)) : '—';
const dateTime = (value) => value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '—';
const statusLabel = {
  draft: 'Rascunho', review: 'Em revisão', awaiting_documents: 'Documentos', awaiting_signature: 'Aguardando assinatura',
  awaiting_signatures: 'Aguardando assinaturas', partially_signed: 'Parcialmente assinado', signed: 'Assinado', active: 'Ativo',
  ended: 'Encerrado', cancelled: 'Cancelado', expired: 'Expirado', locked: 'Versão bloqueada', pending: 'Pendente',
  processing: 'Processando', paid: 'Pago', overdue: 'Atrasado',
};
const expenseOptions = [['iptu', 'IPTU'], ['water', 'Água'], ['electricity', 'Energia'], ['internet', 'Internet'], ['condo', 'Condomínio']];
const leaseVigency = (lease) => {
  if (!lease) return { inForce: false, label: 'Contrato não vigente' };
  if (typeof lease.is_in_force === 'boolean') return { inForce: lease.is_in_force, label: lease.is_in_force ? 'Contrato vigente' : 'Contrato não vigente' };
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const starts = lease.starts_on ? new Date(`${String(lease.starts_on).slice(0, 10)}T00:00:00`) : null;
  const ends = lease.ends_on ? new Date(`${String(lease.ends_on).slice(0, 10)}T23:59:59`) : null;
  const inForce = lease.status === 'active' && (!starts || starts <= today) && (!ends || ends >= today);
  return { inForce, label: inForce ? 'Contrato vigente' : 'Contrato não vigente' };
};

function Brand({ compact = false }) {
  return <div className={`brand ${compact ? 'compact' : ''}`}><img className="brand-logo" src="/logo-locaio.png?v=20260903-2" alt="Locaio" /><div><strong>Locaio</strong>{!compact && <small>by Peter Tecnet</small>}</div></div>;
}

function Toast({ toast }) { return toast ? <div className={`pt-toast ${toast.type || ''}`} role="status">{toast.message}</div> : null; }

function GoogleLogin({ onSuccess, notify }) {
  const ref = useRef(null); const clientId = import.meta.env.VITE_GOOGLE_CLIENT_ID;
  useEffect(() => {
    if (!clientId || !ref.current) return undefined;
    const render = () => {
      if (!window.google?.accounts?.id || !ref.current) return;
      window.google.accounts.id.initialize({ client_id: clientId, callback: async ({ credential }) => {
        try { const response = await api.post('/auth/google', { token_id: credential }); storeSession(response); onSuccess(); }
        catch (error) { notify(errorMessage(error), 'error'); }
      }});
      ref.current.innerHTML = '';
      window.google.accounts.id.renderButton(ref.current, { theme: 'outline', size: 'large', width: Math.min(360, ref.current.clientWidth || 320), text: 'continue_with' });
    };
    if (window.google?.accounts?.id) { render(); return undefined; }
    const script = document.createElement('script'); script.src = 'https://accounts.google.com/gsi/client'; script.async = true; script.defer = true; script.onload = render; document.head.appendChild(script);
    return undefined;
  }, [clientId, notify, onSuccess]);
  return clientId ? <div className="google-login" ref={ref} /> : null;
}

function Auth({ onAuthenticated, notify }) {
  const [mode, setMode] = useState('login'); const [busy, setBusy] = useState(false); const [show, setShow] = useState(false); const [info, setInfo] = useState('');
  const [form, setForm] = useState({ first_name: '', email: '', username: '', password: '', code: '' });
  const login = async (username = form.username, password = form.password) => { const response = await api.post('/auth/login', { username: username.trim(), password }); storeSession(response); return response; };
  const submit = async (event) => {
    event.preventDefault(); setBusy(true); setInfo('');
    try {
      if (mode === 'register') { await api.post('/auth/register', { first_name: form.first_name.trim(), email: form.email.trim(), password: form.password }); await login(form.email, form.password); setMode('verify'); setInfo('Conta criada. Digite o código enviado ao seu e-mail.'); }
      else if (mode === 'verify') { await api.post('/auth/email-verify', { verification_code: form.code.trim() }); onAuthenticated(); }
      else { await login(); onAuthenticated(); }
    } catch (error) { setInfo(errorMessage(error)); } finally { setBusy(false); }
  };
  return <main className="auth-page auth-page-v2">
    <section className="auth-hero"><Brand /><div className="hero-copy"><span className="eyebrow"><FiShield /> gestão imobiliária em uma única jornada</span><h1>Menos operação.<br /><em>Mais patrimônio sob controle.</em></h1><p>Organize imóveis, contratos, assinaturas, cobranças e responsabilidades financeiras em uma experiência simples e confiável.</p><div className="hero-features"><span><FiHome /> Patrimônio</span><span><FiFileText /> Contratos</span><span><FiCreditCard /> Recebimentos</span></div></div><small>Uma plataforma Peter Tecnet.</small></section>
    <section className="auth-panel"><form className="auth-card" onSubmit={submit}><div><span className="eyebrow">Conta Peter Tecnet</span><h2>{mode === 'login' ? 'Acesse seu patrimônio' : mode === 'register' ? 'Crie sua conta' : 'Verifique seu e-mail'}</h2><p>A mesma conta conecta você ao ecossistema Peter Tecnet.</p></div>
      {mode === 'register' && <label>Nome<input required minLength={2} value={form.first_name} onChange={(e) => setForm({ ...form, first_name: e.target.value })} /></label>}
      {mode === 'register' && <label>E-mail<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label>}
      {mode === 'login' && <label>E-mail, usuário, CPF ou telefone<input required autoComplete="username" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} /></label>}
      {['login', 'register'].includes(mode) && <label>Senha<div className="password-field"><input required minLength={8} type={show ? 'text' : 'password'} autoComplete={mode === 'login' ? 'current-password' : 'new-password'} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><button type="button" aria-label={show ? 'Ocultar senha' : 'Mostrar senha'} onClick={() => setShow((v) => !v)}>{show ? <FiEyeOff /> : <FiEye />}</button></div></label>}
      {mode === 'verify' && <label>Código de verificação<input required inputMode="numeric" value={form.code} onChange={(e) => setForm({ ...form, code: e.target.value })} /></label>}
      {info && <div className="inline-alert">{info}</div>}
      <button className="pt-button primary full" disabled={busy}>{busy ? 'Aguarde…' : mode === 'login' ? 'Entrar' : mode === 'register' ? 'Criar conta' : 'Verificar'}</button>
      {mode === 'login' && <><GoogleLogin onSuccess={onAuthenticated} notify={notify} /><button type="button" className="text-button" onClick={() => setMode('register')}>Ainda não tenho conta</button></>}
      {mode !== 'login' && <button type="button" className="text-button" onClick={() => setMode('login')}>Voltar ao login</button>}
    </form></section>
  </main>;
}

function AppShell({ section, selectedLease, user, logout, navigate, children }) {
  const nav = [['dashboard', FiBriefcase, 'Visão geral'], ['properties', FiHome, 'Imóveis'], ['leases', FiFileText, 'Locações']];
  return <div className="pt-app-shell"><aside className="pt-sidebar"><Brand /><div className="pt-sidebar-caption">Gestão de locações</div><nav>{nav.map(([key, Icon, label]) => <button key={key} className={section === key && !(key === 'dashboard' && selectedLease) ? 'active' : ''} onClick={() => navigate(key)}><span className="pt-nav-icon"><Icon /></span><span>{label}</span></button>)}</nav><div className="pt-sidebar-bottom"><div className="pt-account"><span><FiUser /></span><div><b>{user?.first_name || user?.name || 'Minha conta'}</b><small>{user?.email || 'Conta Peter Tecnet'}</small></div></div><button className="pt-logout" onClick={logout}><FiLogOut /> Sair</button></div></aside><header className="pt-mobile-top"><Brand compact /><button onClick={logout} aria-label="Sair"><FiLogOut /></button></header><main className="pt-content">{children}</main><nav className="pt-mobile-nav">{nav.map(([key, Icon, label]) => <button key={key} className={section === key ? 'active' : ''} onClick={() => navigate(key)}><Icon /><span>{key === 'dashboard' ? 'Resumo' : label}</span></button>)}</nav></div>;
}

function Dashboard({ data, leases, properties, onLease }) {
  const active = Number(data?.active_leases || leases.filter((l) => l.status === 'active').length || 0);
  const totalProperties = Number(data?.properties || properties.length || 0); const occupied = properties.filter((p) => p.status === 'occupied').length;
  const pending = Number(data?.pending_amount || 0); const overdue = Number(data?.overdue_amount || 0);
  const statusCounts = ['active', 'awaiting_signature', 'awaiting_documents', 'draft'].map((status) => leases.filter((l) => l.status === status).length);
  return <div className="pt-page"><PageHeader eyebrow="Visão geral" title="Seu patrimônio, sem planilha." description="Acompanhe ocupação, contratos, vencimentos e recebimentos em um painel que mostra o que merece atenção." />
    <section className="pt-metrics-grid"><MetricCard icon={FiHome} label="Imóveis" value={totalProperties} hint={`${occupied} ocupado(s)`} /><MetricCard icon={FiFileText} label="Contratos ativos" value={active} hint={`${leases.length} contrato(s) no total`} tone="success" /><MetricCard icon={FiDollarSign} label="A receber" value={money(pending)} hint="Valores pendentes" tone="info" /><MetricCard icon={FiAlertCircle} label="Em atraso" value={money(overdue)} hint={overdue > 0 ? 'Requer atenção' : 'Nenhuma pendência crítica'} tone={overdue > 0 ? 'danger' : 'success'} /></section>
    <section className="pt-dashboard-grid"><article className="pt-card pt-financial-card"><header><div><span className="pt-eyebrow">Saúde financeira</span><h2>Recebimentos</h2><p>Relação entre valores pendentes e vencidos.</p></div></header><div className="pt-financial-visual"><Donut value={Math.max(0, pending - overdue)} total={Math.max(pending, 1)} label="Dentro do prazo" detail={`${money(Math.max(0, pending - overdue))} do saldo pendente`} /></div></article><article className="pt-card"><header><div><span className="pt-eyebrow">Carteira</span><h2>Ocupação</h2></div></header><Donut value={occupied} total={Math.max(totalProperties, 1)} label="Imóveis ocupados" detail={`${occupied} de ${totalProperties} imóveis`} /></article><article className="pt-card"><header><div><span className="pt-eyebrow">Pipeline</span><h2>Contratos por etapa</h2></div></header><MiniBars values={statusCounts} labels={['Ativos', 'Assin.', 'Docs', 'Rasc.']} /></article></section>
    <section className="pt-two-columns"><article className="pt-card"><header><div><h2>Próximas cobranças</h2></div></header>{data?.next_charges?.length ? <div className="pt-list">{data.next_charges.map((c) => <div className="pt-list-row" key={c.id}><span className="pt-round-icon"><FiCalendar /></span><div><b>{c.description}</b><small>Vence em {date(c.due_date)}</small></div><strong>{money(c.amount)}</strong></div>)}</div> : <EmptyState icon={FiCheck} title="Tudo em dia" description="As próximas cobranças aparecerão aqui." />}</article><article className="pt-card"><header><div><h2>Contratos recentes</h2></div></header>{leases.length ? <div className="pt-list">{leases.slice(0, 6).map((l) => <button className="pt-list-row clickable" key={l.id} onClick={() => onLease(l.id)}><span className="pt-round-icon"><FiKey /></span><div><b>{l.property_name || l.tenant_name}</b><small>{l.tenant_name} · {statusLabel[l.status] || l.status}</small></div><FiChevronRight /></button>)}</div> : <EmptyState icon={FiFileText} title="Nenhuma locação" description="Cadastre um imóvel e crie o primeiro contrato." />}</article></section>
  </div>;
}

const initialProperty = { name: '', type: 'house', use_type: 'residential', postal_code: '', street: '', number: '', complement: '', neighborhood: '', city: '', state: '', bedrooms: '', bathrooms: '', parking_spaces: '', area_m2: '', default_rent_amount: '', default_due_day: 10 };
function Properties({ items, reload, notify, onCreateLease }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [form, setForm] = useState(initialProperty); const [pendingDelete, setPendingDelete] = useState(null);
  const save = async (e) => { e.preventDefault(); setBusy(true); try { await appApi.post('/properties', { ...form, state: form.state.toUpperCase(), bedrooms: form.bedrooms || null, bathrooms: form.bathrooms || null, parking_spaces: form.parking_spaces || null, area_m2: form.area_m2 || null, default_rent_amount: form.default_rent_amount || null }); notify('Imóvel cadastrado.'); setForm(initialProperty); setOpen(false); await reload(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  const remove = async () => { if (!pendingDelete) return; setBusy(true); try { await appApi.delete(`/properties/${pendingDelete.id}`); notify('Imóvel excluído.'); setPendingDelete(null); await reload(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  return <div className="pt-page"><PageHeader eyebrow="Patrimônio" title="Imóveis" description="Uma visão clara de cada ativo, seu status e as próximas ações." action={<button className="pt-button primary" onClick={() => setOpen(true)}><FiPlus /> Novo imóvel</button>} />
    {items.length ? <div className="pt-property-grid">{items.map((p) => { const image = p.image_url || p.photo_url || p.image || p.cover_url; return <article className="pt-property-card" key={p.id}><div className="pt-property-cover" style={image ? { backgroundImage: `url(${image})` } : undefined}>{!image && <div className="pt-property-fallback"><FiHome /><span>{String(p.name || 'IM').slice(0, 2).toUpperCase()}</span></div>}<StatusBadge status={p.status}>{p.status === 'occupied' ? 'Ocupado' : p.status === 'available' ? 'Disponível' : p.status}</StatusBadge></div><div className="pt-property-body"><div><h3>{p.name}</h3><p><FiMapPin /> {p.street}{p.number ? `, ${p.number}` : ''} · {p.city}/{p.state}</p></div><div className="pt-property-details"><span>{p.use_type === 'commercial' ? 'Comercial' : p.use_type === 'mixed' ? 'Misto' : 'Residencial'}</span><b>{p.default_rent_amount ? money(p.default_rent_amount) : 'Valor a definir'}</b></div><div className="pt-card-actions"><button className="pt-button ghost" onClick={() => onCreateLease(p.id)}><FiFileText /> Criar locação</button><button className="pt-icon-button danger" aria-label={`Excluir ${p.name}`} onClick={() => setPendingDelete(p)}><FiTrash2 /></button></div></div></article>; })}</div> : <EmptyState icon={FiHome} title="Cadastre seu primeiro imóvel" description="O imóvel será a base para contratos, vistorias e cobranças." action={<button className="pt-button primary" onClick={() => setOpen(true)}><FiPlus /> Cadastrar imóvel</button>} />}
    <Modal open={open} title="Cadastrar imóvel" eyebrow="Novo patrimônio" onClose={() => setOpen(false)} large><form className="pt-form" onSubmit={save}><div className="pt-form-grid two"><label>Nome do imóvel<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label>Tipo<select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="house">Casa</option><option value="apartment">Apartamento</option><option value="commercial">Comercial</option><option value="land">Terreno</option><option value="other">Outro</option></select></label><label>Uso<select value={form.use_type} onChange={(e) => setForm({ ...form, use_type: e.target.value })}><option value="residential">Residencial</option><option value="commercial">Comercial</option><option value="mixed">Misto</option></select></label><label>CEP<input value={form.postal_code} onChange={(e) => setForm({ ...form, postal_code: e.target.value })} /></label><label className="span-2">Rua / Avenida<input required value={form.street} onChange={(e) => setForm({ ...form, street: e.target.value })} /></label><label>Número<input value={form.number} onChange={(e) => setForm({ ...form, number: e.target.value })} /></label><label>Complemento<input value={form.complement} onChange={(e) => setForm({ ...form, complement: e.target.value })} /></label><label>Bairro<input value={form.neighborhood} onChange={(e) => setForm({ ...form, neighborhood: e.target.value })} /></label><label>Cidade<input required value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /></label><label>UF<input required maxLength={2} value={form.state} onChange={(e) => setForm({ ...form, state: e.target.value })} /></label><label>Aluguel padrão<input type="number" min="0" step="0.01" value={form.default_rent_amount} onChange={(e) => setForm({ ...form, default_rent_amount: e.target.value })} /></label><label>Dia de vencimento<input type="number" min="1" max="31" value={form.default_due_day} onChange={(e) => setForm({ ...form, default_due_day: e.target.value })} /></label></div><div className="pt-modal-actions"><button type="button" className="pt-button secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="pt-button primary" disabled={busy}>{busy ? 'Salvando…' : 'Cadastrar imóvel'}</button></div></form></Modal>
    <ConfirmDialog open={Boolean(pendingDelete)} title="Excluir imóvel" description={pendingDelete ? `Excluir “${pendingDelete.name}”? A exclusão será bloqueada se existir contrato ativo ou aguardando assinatura.` : ''} confirmLabel="Excluir imóvel" danger busy={busy} onConfirm={remove} onCancel={() => setPendingDelete(null)} />
  </div>;
}

const initialLease = { property_id: '', tenant_name: '', tenant_email: '', tenant_phone: '', tenant_tax_id: '', purpose: 'residential', starts_on: '', ends_on: '', rent_amount: '', due_day: 10, deposit_months: 0, guarantee_type: 'none', adjustment_index: 'IPCA', included_expenses: [], tenant_expenses: ['iptu', 'water', 'electricity', 'internet', 'condo'], clausesText: '' };
const leaseSteps = ['Imóvel', 'Inquilino', 'Condições', 'Responsabilidades', 'Revisão'];
function Leases({ items, properties, reload, notify, onLease, requestedProperty, onRequestedPropertyConsumed }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [step, setStep] = useState(0); const [form, setForm] = useState(initialLease);
  useEffect(() => { if (requestedProperty) { setForm((v) => ({ ...v, property_id: String(requestedProperty) })); setStep(0); setOpen(true); onRequestedPropertyConsumed?.(); } }, [requestedProperty, onRequestedPropertyConsumed]);
  const selectedProperty = useMemo(() => properties.find((p) => String(p.id) === String(form.property_id)), [form.property_id, properties]);
  useEffect(() => { if (selectedProperty) setForm((v) => ({ ...v, purpose: selectedProperty.use_type || v.purpose, rent_amount: v.rent_amount || selectedProperty.default_rent_amount || '', due_day: selectedProperty.default_due_day || v.due_day })); }, [selectedProperty]);
  const toggleExpense = (key, target) => setForm((v) => ({ ...v, [target]: v[target].includes(key) ? v[target].filter((x) => x !== key) : [...v[target], key], [target === 'included_expenses' ? 'tenant_expenses' : 'included_expenses']: v[target === 'included_expenses' ? 'tenant_expenses' : 'included_expenses'].filter((x) => x !== key) }));
  const canContinue = step === 0 ? Boolean(form.property_id) : step === 1 ? Boolean(form.tenant_name.trim()) : step === 2 ? Boolean(form.starts_on && form.ends_on && Number(form.rent_amount) > 0 && Number(form.due_day) > 0) : true;
  const save = async () => { setBusy(true); try { const clauses = form.clausesText.split('\n').map((x) => x.trim()).filter(Boolean); const payload = { ...form, property_id: Number(form.property_id), deposit_months: Number(form.deposit_months), clauses }; delete payload.clausesText; const { data } = await appApi.post('/leases', payload); notify('Locação criada. Prepare a proposta antes de enviar o contrato.'); setOpen(false); setStep(0); setForm(initialLease); await reload(); onLease(data?.lease?.id || data?.id); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  return <div className="pt-page"><PageHeader eyebrow="Contratos" title="Locações" description="Do acordo inicial à assinatura e à vigência, com histórico completo de cada decisão." action={<button className="pt-button primary" disabled={!properties.length} onClick={() => { setStep(0); setOpen(true); }}><FiPlus /> Nova locação</button>} />
    {!properties.length && <div className="inline-alert"><FiAlertCircle /> Cadastre ao menos um imóvel antes de criar uma locação.</div>}
    {items.length ? <div className="pt-lease-list"><div className="pt-lease-header"><span>Imóvel / inquilino</span><span>Período</span><span>Aluguel</span><span>Status</span><span /></div>{items.map((l) => <button className="pt-lease-row" key={l.id} onClick={() => onLease(l.id)}><span className="pt-lease-main"><span className="pt-round-icon"><FiHome /></span><span><b>{l.property_name || `Imóvel #${l.property_id}`}</b><small>{l.tenant_name}</small></span></span><span data-label="Período">{date(l.starts_on)}<small>até {date(l.ends_on)}</small></span><strong data-label="Aluguel">{money(l.rent_amount)}</strong><span data-label="Status"><StatusBadge status={l.status}>{statusLabel[l.status] || l.status}</StatusBadge><small>{leaseVigency(l).label}</small></span><FiChevronRight /></button>)}</div> : <EmptyState icon={FiFileText} title="Nenhum contrato ainda" description="Crie a locação, valide as condições com uma proposta e só depois emita o contrato." />}
    <Modal open={open} title="Nova locação" eyebrow={`Etapa ${step + 1} de ${leaseSteps.length}`} onClose={() => setOpen(false)} large><div className="contract-wizard"><div className="contract-wizard-nav">{leaseSteps.map((label, index) => <span key={label} className={index === step ? 'active' : index < step ? 'done' : ''}><i>{index < step ? <FiCheck /> : index + 1}</i>{label}</span>)}</div>
      {step === 0 && <section className="pt-form-section"><h3>Imóvel e finalidade</h3><div className="pt-form-grid two"><label>Imóvel<select required value={form.property_id} onChange={(e) => setForm({ ...form, property_id: e.target.value })}><option value="">Selecione</option>{properties.map((p) => <option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Finalidade<select value={form.purpose} onChange={(e) => setForm({ ...form, purpose: e.target.value })}><option value="residential">Residencial</option><option value="commercial">Comercial</option><option value="mixed">Mista</option></select></label></div></section>}
      {step === 1 && <section className="pt-form-section"><h3>Quem vai alugar?</h3><div className="pt-form-grid two"><label>Nome completo<input required value={form.tenant_name} onChange={(e) => setForm({ ...form, tenant_name: e.target.value })} /></label><label>CPF / CNPJ<input value={form.tenant_tax_id} onChange={(e) => setForm({ ...form, tenant_tax_id: e.target.value })} /></label><label>E-mail<input type="email" value={form.tenant_email} onChange={(e) => setForm({ ...form, tenant_email: e.target.value })} /></label><label>Telefone<input value={form.tenant_phone} onChange={(e) => setForm({ ...form, tenant_phone: e.target.value })} /></label></div></section>}
      {step === 2 && <section className="pt-form-section"><h3>Prazo, aluguel e garantia</h3><div className="pt-form-grid three"><label>Início<input required type="date" value={form.starts_on} onChange={(e) => setForm({ ...form, starts_on: e.target.value })} /></label><label>Fim<input required type="date" value={form.ends_on} onChange={(e) => setForm({ ...form, ends_on: e.target.value })} /></label><label>Aluguel<input required type="number" min="0.01" step="0.01" value={form.rent_amount} onChange={(e) => setForm({ ...form, rent_amount: e.target.value })} /></label><label>Vencimento<input required type="number" min="1" max="31" value={form.due_day} onChange={(e) => setForm({ ...form, due_day: e.target.value })} /></label><label>Caução em aluguéis<select value={form.deposit_months} onChange={(e) => setForm({ ...form, deposit_months: e.target.value, guarantee_type: Number(e.target.value) ? 'deposit' : 'none' })}><option value="0">Sem caução</option><option value="1">1 aluguel</option><option value="2">2 aluguéis</option><option value="3">3 aluguéis</option></select></label><label>Índice de reajuste<input value={form.adjustment_index} onChange={(e) => setForm({ ...form, adjustment_index: e.target.value })} /></label></div></section>}
      {step === 3 && <><section className="pt-form-section"><h3>Responsabilidade pelas contas</h3><div className="pt-expense-grid">{expenseOptions.map(([key, label]) => <div key={key}><b>{label}</b><div className="pt-segmented"><button type="button" className={form.included_expenses.includes(key) ? 'active' : ''} onClick={() => toggleExpense(key, 'included_expenses')}>Incluso</button><button type="button" className={form.tenant_expenses.includes(key) ? 'active' : ''} onClick={() => toggleExpense(key, 'tenant_expenses')}>Inquilino</button></div></div>)}</div></section><section className="pt-form-section"><h3>Cláusulas adicionais</h3><label>Uma cláusula por linha<textarea rows="5" value={form.clausesText} onChange={(e) => setForm({ ...form, clausesText: e.target.value })} /></label></section></>}
      {step === 4 && <section className="wizard-review"><h3>Revise antes de criar</h3><div className="review-grid"><div><small>Imóvel</small><b>{selectedProperty?.name || '—'}</b></div><div><small>Inquilino</small><b>{form.tenant_name}</b></div><div><small>Aluguel</small><b>{money(form.rent_amount)}</b></div><div><small>Vencimento</small><b>Dia {form.due_day}</b></div><div><small>Vigência</small><b>{date(form.starts_on)} — {date(form.ends_on)}</b></div><div><small>Garantia</small><b>{Number(form.deposit_months) ? `${form.deposit_months} aluguel(is)` : 'Sem caução'}</b></div></div><div className="workflow-note"><FiShield /><div><b>Próximo passo: proposta</b><p>A locação será criada como rascunho. Você poderá gerar uma proposta para confirmar as condições antes de emitir a versão contratual para assinatura.</p></div></div></section>}
      <div className="pt-modal-actions"><button type="button" className="pt-button secondary" onClick={() => step ? setStep(step - 1) : setOpen(false)}>{step ? 'Voltar' : 'Cancelar'}</button>{step < leaseSteps.length - 1 ? <button type="button" className="pt-button primary" disabled={!canContinue} onClick={() => setStep(step + 1)}>Continuar <FiChevronRight /></button> : <button type="button" className="pt-button primary" disabled={busy} onClick={save}>{busy ? 'Criando…' : 'Criar locação'}</button>}</div>
    </div></Modal>
  </div>;
}

function ContractStepper({ lease, workflow, documents = [], charges = [] }) {
  const signatures = workflow?.signatures || [];
  const steps = [['Dados', true], ['Documentos', documents.length > 0], ['Contrato', Boolean(workflow || lease.contract_text)], ['Assinaturas', signatures.length >= 2 || lease.status === 'active'], ['Cobranças', charges.length > 0], ['Vigência', leaseVigency(lease).inForce]];
  const current = Math.max(0, steps.findIndex(([, done]) => !done));
  return <div className="pt-stepper">{steps.map(([label, done], index) => <div key={label} className={`${done ? 'done' : ''} ${!done && index === current ? 'current' : ''}`}><span>{done ? <FiCheck /> : index + 1}</span><small>{label}</small></div>)}</div>;
}

function ContractReadiness({ lease, property, documents }) {
  const checks = [
    ['E-mail do inquilino', Boolean(lease.tenant_email)], ['CPF/CNPJ do inquilino', Boolean(lease.tenant_tax_id)],
    ['Endereço do imóvel', Boolean(property.street && property.city && property.state)], ['Vigência definida', Boolean(lease.starts_on && lease.ends_on)],
    ['Valor e vencimento', Number(lease.rent_amount) > 0 && Number(lease.due_day) > 0], ['Documentação anexada', documents.length > 0],
  ];
  const missing = checks.filter(([, ok]) => !ok);
  return <section className={`contract-readiness ${missing.length ? 'attention' : 'ready'}`}><header><FiShield /><div><b>{missing.length ? `${missing.length} ponto(s) para revisar` : 'Contrato pronto para emissão'}</b><p>{missing.length ? 'Complete os dados recomendados antes do envio para assinatura.' : 'Os principais dados do processo estão preenchidos.'}</p></div></header>{missing.length > 0 && <div className="readiness-items">{checks.map(([label, ok]) => <span key={label} className={ok ? 'ok' : 'missing'}>{ok ? <FiCheck /> : <FiAlertCircle />}{label}</span>)}</div>}</section>;
}

function LeaseDetail({ id, user, onBack, notify, refreshAll }) {
  const [data, setData] = useState(null); const [contract, setContract] = useState(null); const [timeline, setTimeline] = useState([]); const [proposal, setProposal] = useState(null);
  const [busy, setBusy] = useState(false); const [uploading, setUploading] = useState(false); const [signer, setSigner] = useState(''); const [amendmentOpen, setAmendmentOpen] = useState(false); const [amendment, setAmendment] = useState({ title: '', label: '', value: '' });
  const load = useCallback(async () => {
    try {
      const [leaseResponse, contractResponse] = await Promise.all([appApi.get(`/leases/${id}`), appApi.get(`/leases/${id}/contract`).catch(() => ({ data: { document: null, timeline: [] } }))]);
      setData(leaseResponse.data); setContract(contractResponse.data?.document || null); setTimeline(contractResponse.data?.timeline || []);
    } catch (error) { notify(errorMessage(error), 'error'); }
  }, [id, notify]);
  useEffect(() => { load(); }, [load]);
  if (!data) return <div className="pt-page"><Skeleton rows={5} cards /></div>;
  const l = data.lease; const p = data.property; const owner = String(l.landlord_user_id) === String(user?.id); const tenant = !owner; const signatures = contract?.signatures || data.signatures || [];
  const latestVersion = contract?.versions?.[0];
  const act = async (fn, success) => { setBusy(true); try { const response = await fn(); if (success) notify(success); await load(); await refreshAll(); return response; } catch (error) { notify(errorMessage(error), 'error'); return null; } finally { setBusy(false); } };
  const generateProposal = async () => { setBusy(true); try { const response = await appApi.post(`/leases/${id}/proposal/generate`); setProposal(response.data?.document || null); notify('Proposta gerada para revisão das condições.'); } catch (error) { notify(errorMessage(error), 'error'); } finally { setBusy(false); } };
  const generate = () => act(() => appApi.post(`/leases/${id}/contract/generate`), contract ? 'Nova versão do contrato criada sem apagar o histórico anterior.' : 'Contrato gerado com snapshot dos dados da locação.');
  const send = () => act(() => appApi.post(`/leases/${id}/contract/send`), 'Versão bloqueada e enviada ao inquilino para assinatura.');
  const schedule = () => act(() => appApi.post(`/leases/${id}/charges/schedule`), 'Cronograma financeiro atualizado.');
  const sign = () => act(() => appApi.post(`/leases/${id}/contract/sign`, { party: owner ? 'landlord' : 'tenant', signer_name: signer || (owner ? (user?.name || user?.first_name || 'Locador') : l.tenant_name), accepted: true }), 'Assinatura eletrônica vinculada à versão imutável.');
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; setUploading(true); const body = new FormData(); body.append('category', 'identity'); body.append('file', file); try { await appApi.post(`/leases/${id}/documents`, body, { headers: { 'Content-Type': 'multipart/form-data' } }); notify('Documento enviado.'); await load(); } catch (error) { notify(errorMessage(error), 'error'); } finally { setUploading(false); event.target.value = ''; } };
  const pay = (charge, method) => act(() => appApi.post(`/leases/${id}/charges/${charge.id}/payment`, { method }), `Cobrança preparada para ${method === 'pix' ? 'Pix' : method === 'boleto' ? 'boleto' : 'cartão'}.`);
  const markPaid = (charge) => act(() => appApi.patch(`/leases/${id}/charges/${charge.id}/paid`, { payment_method: charge.payment_method || 'transfer' }), 'Pagamento marcado como recebido.');
  const saveAmendment = async () => { if (!amendment.title.trim() || !amendment.label.trim() || !amendment.value.trim()) return; const response = await act(() => appApi.post(`/leases/${id}/contract/amendments`, { title: amendment.title.trim(), changes: [{ label: amendment.label.trim(), value: amendment.value.trim() }] }), 'Aditivo criado e vinculado ao contrato original.'); if (response) { setAmendmentOpen(false); setAmendment({ title: '', label: '', value: '' }); } };
  const documentStatus = contract?.status || (l.contract_text ? 'review' : 'draft');
  const content = latestVersion?.content || l.contract_text;
  const canAmend = owner && (l.status === 'active' || contract?.status === 'signed');
  return <div className="pt-page"><button className="pt-back" onClick={onBack}><FiArrowLeft /> Voltar às locações</button><header className="pt-contract-hero"><div><span className="pt-eyebrow">Central do contrato · {String(l.public_id || l.id).slice(0, 8)}</span><h1>{p.name}</h1><p><FiMapPin /> {p.street}{p.number ? `, ${p.number}` : ''} · {p.city}/{p.state}</p></div><div><StatusBadge status={l.status}>{statusLabel[l.status] || l.status}</StatusBadge><small>{leaseVigency(l).label}</small></div></header><ContractStepper lease={l} workflow={contract} documents={data.documents || []} charges={data.charges || []} />
    <section className="pt-metrics-grid compact"><MetricCard icon={FiUser} label="Inquilino" value={l.tenant_name} /><MetricCard icon={FiDollarSign} label="Aluguel" value={money(l.rent_amount)} /><MetricCard icon={FiCalendar} label="Vigência" value={`${date(l.starts_on)} — ${date(l.ends_on)}`} hint={leaseVigency(l).label} /><MetricCard icon={FiShield} label="Versão" value={contract ? `v${contract.current_version}` : 'Não emitida'} hint={statusLabel[documentStatus] || documentStatus} /></section>
    <ContractReadiness lease={l} property={p} documents={data.documents || []} />
    <div className="pt-contract-layout"><main>
      {owner && !contract && <section className="pt-card proposal-card"><header><div><span className="pt-eyebrow">Antes do contrato</span><h2>Proposta de locação</h2><p>Consolide aluguel, prazo, garantia e responsabilidades para revisar as condições antes de emitir o contrato.</p></div><button className="pt-button secondary" onClick={generateProposal} disabled={busy}><FiFileText /> Gerar proposta</button></header>{proposal ? <div className="proposal-preview"><div><StatusBadge status={proposal.status}>{statusLabel[proposal.status] || proposal.status}</StatusBadge><b>{proposal.title}</b><small>Versão {proposal.current_version}</small></div><pre>{proposal.versions?.[0]?.content}</pre></div> : <div className="workflow-note"><FiShield /><div><b>Evite retrabalho</b><p>A proposta registra as condições comerciais antes da minuta contratual definitiva.</p></div></div>}</section>}
      <section className="pt-card contract-workspace"><header><div><span className="pt-eyebrow">Documento versionado</span><h2>Contrato</h2><p>Cada emissão guarda snapshot, hash, participantes, assinaturas e histórico.</p></div><div className="contract-header-actions">{canAmend && <button className="pt-button ghost" onClick={() => setAmendmentOpen(true)}><FiPlus /> Novo aditivo</button>}{owner && !canAmend && <button className="pt-button secondary" onClick={generate} disabled={busy}><FiRefreshCw /> {contract ? 'Criar nova versão' : 'Gerar contrato'}</button>}</div></header>
        {content ? <><div className="contract-version-bar"><div><StatusBadge status={documentStatus}>{statusLabel[documentStatus] || documentStatus}</StatusBadge><span>Versão {contract?.current_version || l.contract_version || 1}</span>{latestVersion?.is_locked ? <span className="locked"><FiShield /> conteúdo bloqueado para assinatura</span> : <span>em revisão</span>}</div>{latestVersion?.content_hash && <code title={latestVersion.content_hash}>hash {latestVersion.content_hash.slice(0, 12)}…</code>}</div><div className="pt-contract-text">{content}</div></> : <EmptyState icon={FiFileText} title="Contrato ainda não emitido" description="Revise a proposta, complete os dados e gere a primeira versão." />}
        {content && <div className="pt-contract-actions">{owner && ['review', 'draft'].includes(documentStatus) && <button className="pt-button secondary" onClick={send} disabled={busy || !l.tenant_email}><FiSend /> Bloquear e enviar para assinatura</button>}<div className="pt-sign-box"><input placeholder="Nome completo do signatário" value={signer} onChange={(e) => setSigner(e.target.value)} /><button className="pt-button primary" onClick={sign} disabled={busy || !['awaiting_signatures', 'partially_signed'].includes(documentStatus)}><FiCheck /> Assinar versão atual</button></div></div>}
        <div className="signature-progress"><header><div><h3>Assinaturas</h3><p>As assinaturas ficam vinculadas ao hash exato da versão aceita.</p></div><b>{signatures.length}/2</b></header><div className="signature-grid">{['landlord', 'tenant'].map((role) => { const party = contract?.parties?.find((x) => x.role === role); const signed = signatures.find((x) => Number(x.document_party_id) === Number(party?.id)) || data.signatures?.find((x) => x.party === role); return <div key={role} className={signed ? 'signed' : ''}><span>{signed ? <FiCheck /> : <FiUser />}</span><div><b>{role === 'landlord' ? 'Locador' : 'Inquilino'}</b><small>{signed ? `Assinado em ${dateTime(signed.signed_at)}` : party?.email || (role === 'tenant' ? l.tenant_email : 'Aguardando assinatura')}</small></div></div>; })}</div></div>
      </section>
      {contract && <section className="pt-card"><header><div><h2>Histórico e versões</h2><p>Registro cronológico das ações e versões do documento.</p></div></header><div className="version-list">{contract.versions?.map((version) => <div key={version.id}><span className={version.is_locked ? 'locked' : ''}>v{version.version}</span><div><b>{statusLabel[version.status] || version.status}</b><small>{dateTime(version.created_at)} · hash {version.content_hash?.slice(0, 12)}…</small></div></div>)}</div><div className="audit-timeline">{timeline.length ? timeline.map((event) => <div key={event.id}><span /><div><b>{event.description || event.event_type}</b><small>{dateTime(event.occurred_at)} · {event.event_type}</small></div></div>) : <small>Nenhum evento de auditoria registrado ainda.</small>}</div></section>}
      <section className="pt-card"><header><div><h2>Documentos de apoio</h2><p>Identificação, comprovantes, vistorias e demais arquivos do processo.</p></div><label className="pt-button secondary"><FiUpload /> {uploading ? 'Enviando…' : 'Enviar documento'}<input hidden type="file" accept="image/*,.pdf" onChange={upload} disabled={uploading} /></label></header>{data.documents?.length ? <div className="pt-list">{data.documents.map((d) => <a className="pt-list-row" key={d.id} href={`${import.meta.env.VITE_API_URL || 'https://api.petertecnet.com.br/api'}/v1/apps/locaio/leases/${id}/documents/${d.id}`} target="_blank" rel="noreferrer"><span className="pt-round-icon"><FiFileText /></span><div><b>{d.name}</b><small>{d.category} · {(Number(d.size || 0) / 1024).toFixed(0)} KB</small></div><FiDownload /></a>)}</div> : <EmptyState icon={FiUpload} title="Nenhum documento" description={tenant ? 'Envie seus documentos para o proprietário concluir o contrato.' : 'Anexe os documentos que sustentam esta locação.'} />}</section>
      <section className="pt-card"><header><div><h2>Cobranças</h2><p>Aluguel, caução e demais obrigações financeiras.</p></div>{owner && <button className="pt-button secondary" onClick={schedule} disabled={busy}><FiCalendar /> Gerar cronograma</button>}</header>{data.charges?.length ? <div className="pt-charge-list">{data.charges.map((c) => <article className="pt-charge" key={c.id}><div><StatusBadge status={c.status}>{statusLabel[c.status] || c.status}</StatusBadge><h3>{c.description}</h3><p>Vencimento {date(c.due_date)}</p></div><strong>{money(c.amount)}</strong><div className="pt-charge-actions">{c.status !== 'paid' && <><button onClick={() => pay(c, 'pix')}>Pix</button><button onClick={() => pay(c, 'boleto')}>Boleto</button><button onClick={() => pay(c, 'card')}>Cartão</button>{owner && <button className="received" onClick={() => markPaid(c)}>Marcar recebido</button>}</>}{c.status === 'paid' && <span className="paid"><FiCheck /> Pago</span>}</div></article>)}</div> : <EmptyState icon={FiCreditCard} title="Sem cobranças" description="Gere o cronograma para criar aluguel e caução automaticamente." />}</section>
    </main><aside><section className="pt-card sticky"><h3>Condições da locação</h3><dl><div><dt>Finalidade</dt><dd>{l.purpose === 'commercial' ? 'Comercial' : l.purpose === 'mixed' ? 'Mista' : 'Residencial'}</dd></div><div><dt>Status da vigência</dt><dd>{leaseVigency(l).label}</dd></div><div><dt>Vencimento</dt><dd>Dia {l.due_day}</dd></div><div><dt>Reajuste</dt><dd>{l.adjustment_index || 'A definir'} / {l.adjustment_frequency_months || 12} meses</dd></div><div><dt>Garantia</dt><dd>{l.guarantee_type === 'deposit' ? `Caução ${money(l.deposit_amount)}` : 'Sem caução'}</dd></div></dl><hr /><h4>Incluso no aluguel</h4><div className="pt-chips">{(l.included_expenses || []).length ? l.included_expenses.map((x) => <span key={x}>{expenseOptions.find((o) => o[0] === x)?.[1] || x}</span>) : <small>Nenhuma despesa marcada como inclusa.</small>}</div><h4>Responsabilidade do inquilino</h4><div className="pt-chips">{(l.tenant_expenses || []).map((x) => <span key={x}>{expenseOptions.find((o) => o[0] === x)?.[1] || x}</span>)}</div></section></aside></div>
    <Modal open={amendmentOpen} title="Criar aditivo" eyebrow="Contrato assinado" onClose={() => setAmendmentOpen(false)}><div className="pt-form"><p>O contrato original permanece imutável. O aditivo será um novo documento vinculado a ele.</p><label>Título<input value={amendment.title} onChange={(e) => setAmendment({ ...amendment, title: e.target.value })} placeholder="Ex.: Aditivo de reajuste" /></label><label>O que será alterado?<input value={amendment.label} onChange={(e) => setAmendment({ ...amendment, label: e.target.value })} placeholder="Ex.: Valor do aluguel" /></label><label>Nova condição<textarea rows="4" value={amendment.value} onChange={(e) => setAmendment({ ...amendment, value: e.target.value })} /></label><div className="pt-modal-actions"><button className="pt-button secondary" onClick={() => setAmendmentOpen(false)}>Cancelar</button><button className="pt-button primary" disabled={busy || !amendment.title || !amendment.label || !amendment.value} onClick={saveAmendment}>Criar aditivo</button></div></div></Modal>
  </div>;
}

export default function AppV3() {
  const [authenticated, setAuthenticated] = useState(Boolean(localStorage.getItem('token'))); const [loading, setLoading] = useState(authenticated); const [section, setSection] = useState('dashboard'); const [selectedLease, setSelectedLease] = useState(null); const [dashboard, setDashboard] = useState(null); const [properties, setProperties] = useState([]); const [leases, setLeases] = useState([]); const [requestedProperty, setRequestedProperty] = useState(null); const [user, setUser] = useState(() => { try { return JSON.parse(localStorage.getItem('user') || 'null'); } catch { return null; } }); const [toast, setToast] = useState(null);
  const notify = useCallback((message, type = 'success') => { setToast({ message, type }); window.clearTimeout(window.__locaioToast); window.__locaioToast = window.setTimeout(() => setToast(null), 4200); }, []);
  const load = useCallback(async () => { if (!localStorage.getItem('token')) { setAuthenticated(false); setLoading(false); return; } setLoading(true); try { const [d, p, l, me] = await Promise.all([appApi.get('/leasing/dashboard'), appApi.get('/properties'), appApi.get('/leases'), appApi.get('/me')]); setDashboard(d.data); setProperties(p.data || []); setLeases(l.data || []); const resolvedUser = me.data?.user || me.data; if (resolvedUser?.id) { setUser(resolvedUser); localStorage.setItem('user', JSON.stringify(resolvedUser)); } setAuthenticated(true); } catch (error) { if (error?.response?.status !== 401) notify(errorMessage(error, 'Não foi possível carregar o Locaio.'), 'error'); } finally { setLoading(false); } }, [notify]);
  useEffect(() => { if (authenticated) load(); }, [authenticated, load]);
  useEffect(() => { const handler = () => setAuthenticated(Boolean(localStorage.getItem('token'))); window.addEventListener('authChanged', handler); return () => window.removeEventListener('authChanged', handler); }, []);
  const logout = async () => { try { await api.post('/auth/logout'); } catch { /* local logout remains valid */ } ['token', 'user', 'access_token', 'auth_token'].forEach((k) => localStorage.removeItem(k)); setAuthenticated(false); };
  const navigate = (next) => { setSection(next); setSelectedLease(null); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const openLease = (leaseId) => { setSelectedLease(leaseId); setSection('leases'); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  const createLeaseForProperty = (propertyId) => { setRequestedProperty(propertyId); setSection('leases'); setSelectedLease(null); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  if (!authenticated) return <><Auth onAuthenticated={() => { setAuthenticated(true); load(); }} notify={notify} /><Toast toast={toast} /></>;
  return <><AppShell section={section} selectedLease={selectedLease} user={user} logout={logout} navigate={navigate}>{loading ? <div className="pt-page"><PageHeader eyebrow="Locaio" title="Organizando seu patrimônio…" description="Carregando imóveis, contratos e indicadores." /><Skeleton rows={4} cards /><Skeleton rows={4} /></div> : selectedLease ? <LeaseDetail id={selectedLease} user={user} onBack={() => setSelectedLease(null)} notify={notify} refreshAll={load} /> : section === 'dashboard' ? <Dashboard data={dashboard} leases={leases} properties={properties} onLease={openLease} /> : section === 'properties' ? <Properties items={properties} reload={load} notify={notify} onCreateLease={createLeaseForProperty} /> : <Leases items={leases} properties={properties} reload={load} notify={notify} onLease={openLease} requestedProperty={requestedProperty} onRequestedPropertyConsumed={() => setRequestedProperty(null)} />}</AppShell><Toast toast={toast} /></>;
}
