import { appApi } from './services/api.js';

const KEY = { collapsed: 'locaio.sidebar.collapsed', section: 'locaio.navigation.section' };
const norm = (v = '') => String(v).normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase();
const safe = (v = '') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const icon = (d) => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${d}"/></svg>`;
const I = { search:icon('M11 4a7 7 0 1 0 4.9 12l4.05 4.05 1.4-1.4-4.05-4.05A7 7 0 0 0 11 4Zm0 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10Z'), bell:icon('M19 16v-5a7 7 0 0 0-5-6.7V3h-4v1.3A7 7 0 0 0 5 11v5l-2 2v1h18v-1l-2-2Zm-12 1V11a5 5 0 0 1 10 0v6H7Zm3 3h4a2 2 0 0 1-4 0Z'), home:icon('M12 3 3 10v11h7v-6h4v6h7V10l-9-7Zm7 16h-3v-6H8v6H5v-8l7-5.4 7 5.4v8Z'), file:icon('M6 2h8l4 4v16H6V2Zm2 2v16h8V8h-4V4H8Z'), collapse:icon('m15.4 7.4-1.4-1.4-6 6 6 6 1.4-1.4-4.6-4.6 4.6-4.6Z') };
let data = { dashboard:{}, properties:[], leases:[] }, contextKey = '', restored = false;
const desktop = () => [...document.querySelectorAll('.sidebar nav button')];
const allNav = () => [...desktop(), ...document.querySelectorAll('.mobile-nav button')];
const findNav = (section) => allNav().find(b => ({dashboard:['Visão geral','Resumo'],properties:['Imóveis'],leases:['Locações']}[section] || []).some(x => b.textContent.includes(x)));
const closePanels = () => document.querySelectorAll('.nav-popover.open').forEach(x => x.classList.remove('open'));
function go(section){ findNav(section)?.click(); localStorage.setItem(KEY.section,section); closePanels(); window.scrollTo({top:0,behavior:'smooth'}); }
function overlays(){
  if(!document.querySelector('.global-search')){ const el=document.createElement('div'); el.className='global-search'; el.setAttribute('role','dialog'); el.setAttribute('aria-modal','true'); el.innerHTML=`<div class="global-search-card"><div class="search-input">${I.search}<input type="search" aria-label="Busca global" placeholder="Buscar imóvel, inquilino ou contrato…"><button type="button">Esc</button></div><div class="search-results"></div></div>`; document.body.appendChild(el); el.addEventListener('click',e=>{if(e.target===el)closeSearch()}); el.querySelector('button').onclick=closeSearch; el.querySelector('input').oninput=e=>search(e.target.value); }
  if(!document.querySelector('.notification-panel')){ const el=document.createElement('aside'); el.className='nav-popover notification-panel'; document.body.appendChild(el); }
}
function openSearch(){ overlays(); closePanels(); const el=document.querySelector('.global-search'); el.classList.add('open'); const input=el.querySelector('input'); input.value=''; search(''); setTimeout(()=>input.focus(),0); }
function closeSearch(){ document.querySelector('.global-search')?.classList.remove('open'); }
function search(q){ const box=document.querySelector('.search-results'); if(!box)return; q=norm(q.trim()); if(!q){box.innerHTML='<div class="search-hint"><b>Busca global</b><span>Pesquise por imóvel, endereço, inquilino ou contrato.</span></div>';return} const ps=data.properties.filter(p=>norm([p.name,p.street,p.city,p.state,p.neighborhood].join(' ')).includes(q)).slice(0,5).map(p=>({s:'properties',i:I.home,t:p.name,d:[p.street,p.city,p.state].filter(Boolean).join(' · ')})); const ls=data.leases.filter(l=>norm([l.property_name,l.tenant_name,l.status,l.public_id].join(' ')).includes(q)).slice(0,6).map(l=>({s:'leases',i:I.file,t:l.property_name||'Locação',d:`${l.tenant_name||'Inquilino'} · ${l.status||'contrato'}`})); const rows=[...ps,...ls]; box.innerHTML=rows.length?rows.map(r=>`<button type="button" data-go="${r.s}">${r.i}<span><b>${safe(r.t)}</b><small>${safe(r.d)}</small></span><em>›</em></button>`).join(''):'<div class="search-hint"><b>Nenhum resultado</b><span>Tente outro termo.</span></div>'; box.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{closeSearch();go(b.dataset.go)}); }
function badges(){ const pending=data.leases.filter(l=>['awaiting_signature','awaiting_documents'].includes(l.status)).length, alerts=pending+(Number(data.dashboard?.overdue_amount||0)>0?1:0); desktop().forEach(b=>{const n=b.textContent.includes('Imóveis')?data.properties.length:b.textContent.includes('Locações')?pending:0; let tag=b.querySelector('.nav-count'); if(!tag){tag=document.createElement('i');tag.className='nav-count';b.appendChild(tag)} tag.textContent=n>99?'99+':n;tag.hidden=!n}); document.querySelectorAll('[data-nav-alert-count]').forEach(x=>{x.textContent=alerts>9?'9+':alerts;x.hidden=!alerts}); }
function notifications(){ overlays(); const panel=document.querySelector('.notification-panel'), pending=data.leases.filter(l=>['awaiting_signature','awaiting_documents'].includes(l.status)).slice(0,5), overdue=Number(data.dashboard?.overdue_amount||0), rows=[]; if(overdue>0)rows.push(['Recebimentos em atraso',new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(overdue)]); pending.forEach(l=>rows.push([l.status==='awaiting_signature'?'Assinatura pendente':'Documentação pendente',`${l.property_name||'Contrato'} · ${l.tenant_name||'Inquilino'}`])); panel.innerHTML=`<header><div><small>CENTRAL DE ATENÇÃO</small><h3>Notificações</h3></div><button type="button">×</button></header><div class="notification-list">${rows.length?rows.map(r=>`<button type="button" data-go="leases"><i></i><span><b>${safe(r[0])}</b><small>${safe(r[1])}</small></span></button>`).join(''):'<div class="all-clear"><b>Tudo sob controle</b><span>Nenhuma pendência importante agora.</span></div>'}</div>`; panel.querySelector('header button').onclick=closePanels;panel.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go('leases')); }
async function refresh(){ if(!localStorage.getItem('token'))return; try{const[d,p,l]=await Promise.all([appApi.get('/leasing/dashboard'),appApi.get('/properties'),appApi.get('/leases')]);data={dashboard:d.data||{},properties:p.data||[],leases:l.data||[]};badges();notifications()}catch{/* tela principal já trata indisponibilidade */} }
function shell(){ const sidebar=document.querySelector('.sidebar'); if(!sidebar||sidebar.dataset.navRuntime)return; sidebar.dataset.navRuntime='1'; document.documentElement.classList.toggle('sidebar-collapsed',localStorage.getItem(KEY.collapsed)==='1'); const tools=document.createElement('div');tools.className='nav-toolbar';tools.innerHTML=`<button class="nav-tool search-trigger" type="button">${I.search}<span>Buscar</span><kbd>⌘K</kbd></button><button class="nav-tool icon-only notification-trigger" type="button" aria-label="Notificações">${I.bell}<i data-nav-alert-count hidden></i></button>`;sidebar.querySelector('.brand')?.after(tools);tools.querySelector('.search-trigger').onclick=openSearch;tools.querySelector('.notification-trigger').onclick=e=>{e.stopPropagation();document.querySelector('.notification-panel')?.classList.toggle('open')}; const quick=document.createElement('div');quick.className='quick-actions';quick.innerHTML=`<small>ATALHOS</small><div><button type="button" data-go="properties">${I.home}<span>Imóvel</span></button><button type="button" data-go="leases">${I.file}<span>Locação</span></button></div>`;sidebar.querySelector('nav')?.after(quick);quick.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go)); const col=document.createElement('button');col.type='button';col.className='sidebar-collapse';col.innerHTML=`${I.collapse}<span>Recolher menu</span>`;sidebar.querySelector('.sidebar-bottom')?.prepend(col);col.onclick=()=>{const v=!document.documentElement.classList.contains('sidebar-collapsed');document.documentElement.classList.toggle('sidebar-collapsed',v);localStorage.setItem(KEY.collapsed,v?'1':'0');col.querySelector('span').textContent=v?'Expandir menu':'Recolher menu'}; desktop().forEach(b=>b.onclick=(()=>{const old=b.onclick;return e=>{old?.call(b,e);localStorage.setItem(KEY.section,b.textContent.includes('Imóveis')?'properties':b.textContent.includes('Locações')?'leases':'dashboard')}})()); badges(); }
function context(){ const content=document.querySelector('.content');if(!content)return;const active=desktop().find(b=>b.classList.contains('active'))?.querySelector('span')?.textContent||'Visão geral',detail=document.querySelector('.contract-hero h1')?.textContent||'',key=`${active}|${detail}`;if(key===contextKey)return;contextKey=key;let c=content.querySelector('.app-breadcrumb');if(!c){c=document.createElement('div');c.className='app-breadcrumb';content.prepend(c)}c.innerHTML=`<button type="button">Locaio</button><span>›</span><b>${safe(active)}</b>${detail?`<span>›</span><strong>${safe(detail)}</strong>`:''}`;c.querySelector('button').onclick=()=>go('dashboard');desktop().forEach(b=>b.classList.contains('active')?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')); }
function tick(){ overlays();shell();context();if(!restored&&desktop().length){restored=true;const s=localStorage.getItem(KEY.section);if(s&&s!=='dashboard')findNav(s)?.click()} }
function boot(){tick();refresh();setInterval(tick,500);setInterval(refresh,60000);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape'){closeSearch();closePanels()}});document.addEventListener('click',e=>{if(!e.target.closest('.notification-panel,.notification-trigger'))closePanels()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
