import { useEffect, useState } from 'react';
import { FiAlertTriangle, FiCamera, FiDollarSign, FiDownload, FiFileText, FiHome, FiMapPin, FiShield, FiTool } from 'react-icons/fi';
import { APP_SLUG, API_BASE_URL } from './services/api.js';

const money = (value) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value || 0));
const date = (value) => value ? new Intl.DateTimeFormat('pt-BR').format(new Date(`${String(value).slice(0,10)}T12:00:00`)) : '—';
const apiPath = (token, suffix = '') => `${API_BASE_URL}/v1/apps/${APP_SLUG}/shared-assets/${token}${suffix}`;

export default function SharedAssetPage({ token }) {
  const [data, setData] = useState(null); const [error, setError] = useState('');
  useEffect(() => { let active = true; fetch(apiPath(token), { headers: { Accept: 'application/json', 'X-Peter-App': APP_SLUG } }).then(async (r) => { const body = await r.json().catch(() => ({})); if (!r.ok) throw new Error(body.message || body.error || 'Compartilhamento inválido ou expirado.'); return body; }).then((body) => active && setData(body)).catch((e) => active && setError(e.message)); return () => { active = false; }; }, [token]);
  const download = async (file) => { const r = await fetch(apiPath(token, `/files/${file.id}`), { headers: { 'X-Peter-App': APP_SLUG } }); if (!r.ok) return; const blob = await r.blob(); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = file.original_name || 'arquivo'; a.click(); URL.revokeObjectURL(url); };
  if (error) return <main className="share-page"><section className="share-card share-error"><FiAlertTriangle /><h1>Acesso indisponível</h1><p>{error}</p><small>O link pode ter expirado ou ter sido revogado pelo proprietário.</small></section></main>;
  if (!data) return <main className="share-page"><section className="share-card"><div className="share-loader" /><h2>Carregando patrimônio compartilhado…</h2></section></main>;
  const p = data.asset || {}; const health = data.health || {}; const f = data.financial?.summary || {}; const address = [p.street && `${p.street}${p.number ? `, ${p.number}` : ''}`, p.neighborhood, p.city && p.state ? `${p.city}/${p.state}` : p.city].filter(Boolean).join(' · ');
  return <main className="share-page"><header className="share-brand"><div><span><FiHome /></span><div><b>Locaio</b><small>by Peter Tecnet</small></div></div><em><FiShield /> Acesso temporário · expira {date(data.share?.expires_at)}</em></header><section className="share-hero"><div><span className="share-eyebrow">Patrimônio compartilhado</span><h1>{p.name || 'Imóvel'}</h1><p><FiMapPin /> {address}</p></div><div className={`share-score ${health.grade || ''}`}><small>Saúde</small><strong>{health.score ?? '—'}<span>/100</span></strong></div></section><section className="share-metrics"><article><small>Status</small><strong>{p.status || '—'}</strong></article><article><small>Área</small><strong>{p.area_m2 ? `${p.area_m2} m²` : '—'}</strong></article><article><small>Quartos</small><strong>{p.bedrooms ?? '—'}</strong></article><article><small>Banheiros</small><strong>{p.bathrooms ?? '—'}</strong></article>{data.financial && <><article><small>Resultado líquido 12m</small><strong>{money(f.net_result_12m)}</strong></article><article><small>Em atraso</small><strong>{money(f.overdue)}</strong></article></>}</section>{data.files?.length > 0 && <section className="share-section"><h2><FiFileText /> Arquivos liberados</h2><div className="share-list">{data.files.map((file) => <button key={file.id} onClick={() => download(file)}><span><FiFileText /></span><div><b>{file.original_name}</b><small>{file.context || file.group || 'arquivo'}</small></div><FiDownload /></button>)}</div></section>}{data.inspections?.length > 0 && <section className="share-section"><h2><FiCamera /> Vistorias</h2><div className="share-grid">{data.inspections.map((item) => <article key={item.id}><b>{item.type}</b><small>{date(item.occurred_at)}</small><p>{item.summary || 'Sem observações.'}</p></article>)}</div></section>}{data.maintenance?.length > 0 && <section className="share-section"><h2><FiTool /> Manutenções</h2><div className="share-grid">{data.maintenance.map((item) => <article key={item.id}><b>{item.title}</b><small>{item.status} · {item.priority}</small><p>{item.description || 'Sem descrição.'}</p></article>)}</div></section>}{data.financial && <section className="share-section"><h2><FiDollarSign /> Resumo financeiro liberado</h2><div className="share-metrics"><article><small>Receita bruta 12m</small><strong>{money(f.gross_income_12m)}</strong></article><article><small>Despesas 12m</small><strong>{money(Number(f.owner_expenses_12m || 0) + Number(f.maintenance_cost_12m || 0))}</strong></article><article><small>Rentabilidade líquida</small><strong>{f.net_yield_12m == null ? '—' : `${Number(f.net_yield_12m).toFixed(2)}%`}</strong></article></div></section>}<footer className="share-footer"><FiShield /> Este acesso é limitado pelo proprietário e não concede acesso à conta dele.</footer></main>;
}
